"""Configuration constants for the RGB-D indoor navigation controller.

This module contains static tunables only. Runtime Webots devices, mutable
mission state and sensor buffers stay in rgbd_navigation_cleaner.py so the
controller still owns sensors and motors from one process.
"""

import math

SHOW_WINDOWS = True
SAVE_FRAMES = False
SAVE_EVERY_N_STEPS = 8
PERFORMANCE_MODE = True
SHOW_RGB_DEBUG_WINDOW = False
SHOW_OCCUPANCY_MAP_WINDOW = False
ASYNC_DEBUG_VIEWER_ENABLED = True
DEPTH_MAP_UPDATE_STEPS = 2
CV_MAP_UPDATE_STEPS = 2
UNDER_SURFACE_UPDATE_STEPS = 3
ORB_DEBUG_ENABLED = False
ORB_DEBUG_UPDATE_STEPS = 8
WINDOW_UPDATE_STEPS = 30
DEBUG_PRINT_INTERVAL_SEC = 18.0
DEBUG_VERBOSE_CONSOLE = False
# Per-run debug log file (Notepad-friendly .txt next to the controller). Truncated on
# every startup, so each run leaves one fresh full-detail trace. It logs the VERBOSE
# telemetry line (far richer than the compact console line) plus extra counts, written
# every DEBUG_LOG_INTERVAL_SEC (more often than the console).
DEBUG_LOG_TO_FILE = True
DEBUG_LOG_FILE_NAME = "debug_log.txt"
DEBUG_LOG_INTERVAL_SEC = 4.0
PERF_PROFILER_ENABLED = True
PERF_EMA_ALPHA = 0.18
PERF_DEBUG_INCLUDE = ("loop", "io", "clean", "depthMap", "cv", "under", "struct", "planner", "noise", "fp", "segment", "render")
PERF_THROTTLE_WHILE_ROUTE_COMMIT = True
DEPTH_ROUTE_COMMIT_MAP_UPDATE_STEPS = 3
CV_ROUTE_COMMIT_MAP_UPDATE_STEPS = 4
UNDER_ROUTE_COMMIT_UPDATE_STEPS = 7
STRUCTURAL_ROUTE_COMMIT_UPDATE_STEPS = 4
PLANNER_ROUTE_COMMIT_UPDATE_STEPS = 260
PLANNER_POST_ABORT_FORCE_SEC = 1.40
WINDOW_ROUTE_COMMIT_UPDATE_STEPS = 60
OBJECTIVE_NOISE_FILTER_CACHE_ENABLED = True
OBJECTIVE_NOISE_FILTER_UPDATE_STEPS = 70
FOOTPRINT_MAP_CACHE_ENABLED = True
FOOTPRINT_MAP_CACHE_STEPS = 45
FOOTPRINT_VALUE_CACHE_ENABLED = True
FOOTPRINT_VALUE_CACHE_STEPS = 45
ADAPTIVE_LOAD_SHEDDING_ENABLED = True
ADAPTIVE_LOAD_SHEDDING_LOOP_MS = 48.0
ADAPTIVE_LOAD_SHEDDING_EMA_MS = 42.0
ADAPTIVE_LOAD_SHEDDING_PLANNER_MULT = 2
ADAPTIVE_LOAD_SHEDDING_MAPPING_MULT = 2
ADAPTIVE_LOAD_SHEDDING_WINDOW_MULT = 2
FRONTIER_DIRECT_MAPPING_MIN_REPLAN_STEPS_WHEN_STOPPED = 520
FRONTIER_DIRECT_MAPPING_STOPPED_MOVE_EPS_M = 0.10
FAST_DEBUG_RENDER_ENABLED = True
FAST_DEBUG_RENDER_MIN_STEPS = 45
FAST_DEBUG_RENDER_ROUTE_STEPS = 80
EXPLORATION_COVERAGE_ARBITRATION_ENABLED = True
EXPLORE_PRIORITY_MAX_COVERAGE_PERCENT = 62.0
EXPLORE_PRIORITY_FORCE_FRONTIER_CELLS = 380
EXPLORE_PRIORITY_MIN_FRONTIER_CELLS = 850
EXPLORE_FRONTIER_COMMIT_ENABLED = True
EXPLORE_FRONTIER_TARGET_RATIO_MIN = 0.10
EXPLORE_FRONTIER_REWARD = 21.0
EXPLORE_FRONTIER_RATIO_REWARD = 18.0
EXPLORE_FRONTIER_MAX_ROUTE_COST_M = 2.15
EXPLORE_FRONTIER_MAX_STRAIGHT_DIST_M = 2.35
EXPLORE_FRONTIER_MAX_TURN_FRAC = 0.82
EXPLORE_FRONTIER_MIN_SCORE = 2.5
EXPLORE_FRONTIER_LOCAL_RADIUS_M = 0.46
EXPLORE_FRONTIER_MIN_LOCAL_CELLS = 12
EXPLORE_UNCLEANED_LOCAL_MAX_DIST_M = 0.95
EXPLORE_UNCLEANED_LOCAL_MAX_ROUTE_COST_M = 1.20
EXPLORE_UNCLEANED_LOCAL_LATERAL_M = 0.62
EXPLORE_UNCLEANED_BACKTRACK_FORWARD_M = -0.08
EXPLORE_UNCLEANED_BACKTRACK_TURN_FRAC = 0.52
EXPLORE_UNCLEANED_BACKTRACK_MIN_COST_M = 0.62
EXPLORE_UNCLEANED_IMPORTANT_COMP_CELLS = 520
EXPLORE_UNCLEANED_IMPORTANT_FOOTPRINT_GAIN = 420
EXPLORE_UNCLEANED_IMPORTANT_SEGMENT_GAIN = 520
EXPLORE_UNCLEANED_IMPORTANT_MISSED_BONUS = 5.0
EXPLORE_UNCLEANED_BACKTRACK_PENALTY = 13.5
EXPLORE_UNCLEANED_SIDE_PENALTY = 4.0
EXPLORE_FRONTIER_STICKY_BREAK_MARGIN = 1.0
PLANNER_INTENT_EXPAND_MAP = "EXPAND_MAP"
PLANNER_INTENT_CLEAN_KNOWN = "CLEAN_KNOWN"
PLANNER_INTENT_FINISH_CLEANUP = "FINISH_CLEANUP"
PLANNER_INTENT_MIN_FRONTIER_CELLS_EARLY = max(120, EXPLORE_PRIORITY_FORCE_FRONTIER_CELLS // 2)
PLANNER_INTENT_EXPAND_FRONTIER_CELLS = EXPLORE_PRIORITY_FORCE_FRONTIER_CELLS
PLANNER_INTENT_HIGH_COVERAGE_FRONTIER_CELLS = EXPLORE_PRIORITY_MIN_FRONTIER_CELLS
FRONTIER_COMPONENT_TARGETING_ENABLED = True
EXPLORE_FRONTIER_VANTAGE_RADIUS_M = 0.62
EXPLORE_FRONTIER_VANTAGE_MIN_LOCAL_CELLS = 22
EXPLORE_FRONTIER_LOCAL_BONUS_SCALE = 0.030
EXPLORE_FRONTIER_LOCAL_BONUS_MAX = 9.0
EXPLORE_FRONTIER_COMPONENT_BONUS_SCALE = 0.018
EXPLORE_FRONTIER_COMPONENT_BONUS_MAX = 18.0
EXPLORE_FRONTIER_OPEN_AREA_BONUS_SCALE = 0.006
EXPLORE_FRONTIER_OPEN_AREA_BONUS_MAX = 8.0
ACTIVE_RGBD_SCAN_ENABLED = True
ACTIVE_SCAN_TRIGGER_FRONTIER_CELLS = 1100
ACTIVE_SCAN_TRIGGER_UNKNOWN_CELLS = 2600
ACTIVE_SCAN_TRIGGER_RADIUS_M = 1.55
ACTIVE_SCAN_MIN_FRONT_CLEAR_M = 0.34
ACTIVE_SCAN_MIN_BODY_CLEAR_M = 0.080
ACTIVE_SCAN_COOLDOWN_SEC = 95.0
ACTIVE_SCAN_SPATIAL_COOLDOWN_M = 2.15
ACTIVE_SCAN_YAW_OFFSETS_DEG = (0, -32, 32, 0)
ACTIVE_SCAN_TOLERANCE_DEG = 3.0
# Bumped 0.42 -> 0.55 so that after the new settle delay there is still a clean
# stationary mapping window of ~0.3s per yaw (the robot coasts for the first ~0.12s
# after hitting the yaw, which is now excluded from fusion).
ACTIVE_SCAN_DWELL_SEC = 0.55
ACTIVE_SCAN_TIMEOUT_SEC = 5.8
ACTIVE_SCAN_TURN_KP = 2.00
ACTIVE_SCAN_TURN_MIN_SPEED = 0.34
ACTIVE_SCAN_TURN_MAX_SPEED = 0.82
ACTIVE_SCAN_DWELL_MAP_MIN_REMAIN_SEC = 0.08
# (2) Settle-before-fuse: don't map the dwell ENTRY (robot still coasting from the
# turn); only start fusing once it has held the target yaw this long.
ACTIVE_SCAN_DWELL_SETTLE_SEC = 0.12
# (1) Strict still-gate for scan-dwell fusion (vs the global TURN_MAPPING_OMEGA_LIMIT
# of 0.12): only fuse a dwell frame when residual rotation is truly small (~3.4 deg/s),
# so leftover coast after the turn cannot smear the point cloud.
ACTIVE_SCAN_DWELL_OMEGA_LIMIT = 0.06
POST_TURN_RGBD_SNAPSHOT_ENABLED = True
POST_TURN_RGBD_SNAPSHOT_SETTLE_SEC = 0.22
POST_TURN_RGBD_SNAPSHOT_CAPTURE_SEC = 0.72
POST_TURN_RGBD_SNAPSHOT_SEC = POST_TURN_RGBD_SNAPSHOT_SETTLE_SEC + POST_TURN_RGBD_SNAPSHOT_CAPTURE_SEC
POST_TURN_RGBD_SNAPSHOT_MIN_FRAMES = 4
POST_TURN_RGBD_SNAPSHOT_MIN_WRITES = 1
POST_TURN_RGBD_SNAPSHOT_MAX_SEC = 1.25
POST_TURN_RGBD_SNAPSHOT_FORCE_EVERY_TICK = True
POST_TURN_ROUTE_PIVOT_MIN_ERR_DEG = 16.0
POST_TURN_ROUTE_PIVOT_MIN_SEC = 0.18
ACTIVE_SCAN_FORCE_MAP_EVERY_TICK = False
ACTIVE_SCAN_RESPECT_ROUTE_CANDIDATE_ENABLED = True
ACTIVE_SCAN_CANDIDATE_ROUTE_MAX_COST_M = 2.40
EXPLORATION_FRONTIER_ONLY_OWNER_GATE_ENABLED = True
EXPLORATION_FRONTIER_ONLY_MIN_COVERAGE_PERCENT = 48.0
EXPLORATION_FRONTIER_ONLY_MIN_FRONTIER_CELLS = PLANNER_INTENT_MIN_FRONTIER_CELLS_EARLY
HYBRID_LOCAL_MOTION_RESTORE_ENABLED = True
# Short-route exception inside hybrid-row mode: if a nearby frontier route is
# already computed and passes safety checks, commit it instead of continuing
# ROW_FORWARD — prevents the robot from ignoring a visible nearby frontier.
EXPLORATION_FRONTIER_HYBRID_SHORT_COMMIT_ENABLED = True
EXPLORATION_FRONTIER_HYBRID_SHORT_COMMIT_MAX_COST_M = 3.00  # Round 6w: 1.80->3.00. Below this the robot only "drove forward" (frontier-direct/holdDrive = raw forward, lots of wall bouncing) toward far frontiers instead of committing the planned wavefront route; 3.0m lets medium frontier routes commit (safety still gated by coverage_candidate_is_committable)
# Obstacle-boundary vantage frontiers (kind=4 "obs-boundary"):
# When an obstacle cluster has unexplored gray cells on its sides, generate
# vantage targets just outside the cluster so the robot navigates there to
# capture the unseen faces rather than relying on accidental close passes.
OBS_BOUNDARY_FRONTIER_ENABLED = True
OBS_BOUNDARY_FRONTIER_MIN_CLUSTER_CELLS = 80
OBS_BOUNDARY_FRONTIER_MIN_ADJACENT_UNKNOWN = 30
OBS_BOUNDARY_FRONTIER_APPROACH_M = 0.28
OBS_BOUNDARY_FRONTIER_MIN_LOCAL_CELLS = 8
# Round 6s: obstacle-inspection vantage as a first-class EXPLORATION target.  Until now
# kind=4 (vantage beside an obstacle with unseen faces) was discarded during frontier
# exploration (planner kept only kind=2), so the robot never diverted to map/fill
# furniture and just chased open frontiers along walls.  These rewards are raised to be
# competitive with frontier scores and a close-bonus makes the robot divert to a NEARBY
# obstacle (without crossing the room for a far one).  Set the flag False to revert.
OBS_BOUNDARY_FRONTIER_EXPLORATION_TARGET = True
OBS_BOUNDARY_FRONTIER_REWARD = 26.0        # was 9.5 (uncompetitive vs frontier base 21 + bonuses)
OBS_BOUNDARY_FRONTIER_BONUS_SCALE = 0.06   # was 0.04; bonus grows with nearby unseen-obstacle-boundary cells
OBS_BOUNDARY_FRONTIER_BONUS_MAX = 16.0     # was 5.0
OBS_BOUNDARY_FRONTIER_CLOSE_BONUS = 28.0   # proximity bonus, full when adjacent, 0 at NEAR_RADIUS (LOCAL_FIRST pattern)
OBS_BOUNDARY_FRONTIER_NEAR_RADIUS_M = 1.6  # divert to obstacle only when within this range
OBS_BOUNDARY_FRONTIER_MIN_COVERAGE_PERCENT = 28.0
EXPLORATION_FRONTIER_SINGLE_POINT_COMMIT_ENABLED = True
EXPLORATION_FRONTIER_SINGLE_POINT_MAX_COST_M = 0.90
EXPLORATION_FRONTIER_SINGLE_POINT_MAX_STRAIGHT_M = 0.95
EXPLORATION_FRONTIER_SINGLE_POINT_MAX_TURN_FRAC = 0.58
FRONTIER_DIRECT_MAPPING_ENABLED = True
FRONTIER_DIRECT_MAPPING_MAX_COVERAGE_PERCENT = 46.0
FRONTIER_DIRECT_MAPPING_MIN_FRONT_CLEAR_M = 0.42
FRONTIER_DIRECT_MAPPING_MIN_CENTER_CLEAR_M = 0.34
FRONTIER_DIRECT_MAPPING_MIN_BODY_CLEAR_M = 0.070
FRONTIER_DIRECT_MAPPING_PLANNER_STEPS = 420
FRONTIER_DIRECT_MAPPING_FORCE_REPLAN_DIST_M = 1.05
FRONTIER_DIRECT_MAPPING_HOLD_IF_ROUTE_OK = True
FRONTIER_DIRECT_UNSAFE_RECOVERY_ENABLED = True
FRONTIER_DIRECT_UNSAFE_RECOVERY_FRONT_M = 0.32
FRONTIER_DIRECT_UNSAFE_RECOVERY_BODY_M = 0.070
FRONTIER_DIRECT_UNSAFE_RECOVERY_COOLDOWN_SEC = 5.0
FRONTIER_DIRECT_UNSAFE_BLACKLIST_RADIUS_M = 0.86
EXPLORATION_FRONTIER_ONLY_SNAPSHOT_COOLDOWN_SEC = 4.8
EXPLORATION_FRONTIER_ONLY_SNAPSHOT_MIN_FRONT_CLEAR_M = 0.30
EXPLORATION_FRONTIER_ONLY_SNAPSHOT_MIN_BODY_CLEAR_M = 0.070
EXPLORATION_FRONTIER_ONLY_STALL_WATCHDOG_ENABLED = True
# Anti-freeze: hand motion back to ROW_FORWARD if the frontier-only gate has held
# a stationary robot (owner=NONE) this long with no committable route, instead of
# standing still until the slower blacklist/dock escalation fires.
EXPLORATION_FRONTIER_ONLY_HOLD_RELEASE_SEC = 15.0
# Kill-the-hold: when a frontier candidate has a route that is NOT committable,
# the gate used to FREEZE owner=NONE and wait (relying on snapshots/hold-release).
# That produced the long scan/snapshot/hold churn with cov frozen.  Instead, hand
# motion to ROW_FORWARD so the robot keeps driving and gathering RGB-D evidence
# (and leaves the dead spot); the progress governor + blacklist still redirect it.
# Periodic perception snapshots above this still fire.  Set False to restore hold.
EXPLORATION_FRONTIER_ONLY_HOLD_DRIVE_INSTEAD = True
EXPLORATION_FRONTIER_ONLY_STALL_TIMEOUT_SEC = 12.0
EXPLORATION_FRONTIER_ONLY_STALL_POSE_EPS_M = 0.07
EXPLORATION_FRONTIER_ONLY_STALL_HEADING_EPS_RAD = math.radians(18.0)
# Coverage-progress stall: fires even when the robot is physically moving but
# map coverage has not grown.  Catches the "washing machine" loop where recovery
# maneuvers (CONTACT_BACKUP / GRID_REALIGN) continuously reset the pose-based
# stall timer while the robot bounces in a blocked frontier zone.
# Require a MEANINGFUL coverage gain to reset the coverage-stall timer.  The
# right-obstacle camp creeps coverage up in +0.2/+0.4% steps that kept resetting
# the old 0.35% threshold, so the "washing-machine" watchdog never matured and
# the robot ground on the same obstacle for minutes.  0.50% ignores that creep.
EXPLORATION_FRONTIER_ONLY_STALL_COV_GAIN_PERCENT = 0.50
EXPLORATION_FRONTIER_ONLY_STALL_COV_TIMEOUT_SEC = 55.0
EXPLORATION_FRONTIER_ONLY_STALL_RETURN_TIMEOUT_SEC = 46.0
EXPLORATION_FRONTIER_ONLY_STALL_RETURN_MIN_COVERAGE_PERCENT = 47.5
# Bite: when the watchdog blacklists a camped region (e.g. the right obstacle's
# unresolvable hidden face that yields scan=nogain forever), the suppression must
# be wide and long enough that the robot is actually pushed off to map the real
# interior, instead of stepping just outside a small disc and re-approaching the
# same face.  0.68m/95s was too weak for a multi-cell obstacle silhouette.
EXPLORATION_FRONTIER_ONLY_STALL_BLACKLIST_RADIUS_M = 1.05
EXPLORATION_FRONTIER_ONLY_STALL_BLACKLIST_SEC = 200.0
EXPLORATION_FRONTIER_ONLY_STALL_MAX_BLACKLISTS_BEFORE_DOCK = 4

# Late map-completion priority: when the map still contains coherent unknown
# pockets inside/near the known room, they must outrank easy wall-side frontiers.
COMPLETION_PRIORITY_ENABLED = True
COMPLETION_PRIORITY_MIN_COVERAGE_PERCENT = 34.0
COMPLETION_PRIORITY_MIN_COMPONENT_CELLS = 65
COMPLETION_PRIORITY_MAX_COMPONENT_CELLS = 22000
COMPLETION_PRIORITY_NEAR_CLEANABLE_M = 0.82
COMPLETION_PRIORITY_OBSTACLE_NEAR_M = 0.20
COMPLETION_PRIORITY_BOUNDARY_BAND_M = 0.52
COMPLETION_PRIORITY_MIN_CLEAN_EDGE_CELLS = 20
COMPLETION_PRIORITY_FRONTIER_DILATE_M = 0.13
COMPLETION_PRIORITY_LOCAL_RADIUS_M = 0.74
COMPLETION_PRIORITY_MIN_LOCAL_CELLS = 20
COMPLETION_PRIORITY_REWARD = 32.0
COMPLETION_PRIORITY_LOCAL_BONUS_SCALE = 0.055
COMPLETION_PRIORITY_LOCAL_BONUS_MAX = 38.0
COMPLETION_PRIORITY_FORCE_ROUTE_COVERAGE_PERCENT = 37.0
COMPLETION_PRIORITY_FORCE_ROUTE_CELLS = 260
COMPLETION_PRIORITY_COMPLETE_BLOCK_CELLS = 260
COMPLETION_PRIORITY_COMPLETE_BLOCK_COMPS = 2
COMPLETION_PRIORITY_STALL_DOCK_BLOCK_CELLS = 420

# Prevent repeated late passes along the same already-seen wall band while
# important completion/gray pockets remain elsewhere.  This is a scoring penalty
# only; it does not change the online map or remove true walls/obstacles.
RIGHT_WALL_REPEAT_SUPPRESS_ENABLED = True
# Engage the wall-repeat penalty EARLY.  The robot was pacing the right wall up/down
# at cov~31% (nearest committable frontiers are the beyond-the-wall ghosts right next
# to it) instead of committing to the large unexplored LEFT half.  The penalty only
# applies to a RE-visited edge band near the robot, so first-pass exploration is not
# punished; lowering the coverage gate just lets it redirect to the far frontier
# sooner.  The gray gate was the wrong proxy here (the unexplored left is frontier,
# not interior gray), so drop it to 0.  Pure scoring nudge — does not touch hypObs,
# planning masks, or walls.
RIGHT_WALL_REPEAT_SUPPRESS_MIN_COVERAGE_PERCENT = 24.0
RIGHT_WALL_REPEAT_SUPPRESS_MIN_GRAY_CELLS = 0
RIGHT_WALL_REPEAT_SUPPRESS_EDGE_BAND_M = 1.10
RIGHT_WALL_REPEAT_SUPPRESS_RECENT_RATIO = 0.18
RIGHT_WALL_REPEAT_SUPPRESS_PENALTY = 42.0
RIGHT_WALL_REPEAT_SUPPRESS_WITH_COMPLETION_PENALTY = 68.0
RIGHT_WALL_REPEAT_SUPPRESS_NEAR_ROBOT_M = 2.25
FRONTIER_FALLBACK_DIRECT_ROUTE_ENABLED = True
FRONTIER_FALLBACK_DIRECT_MAX_BLOCKED_RATIO = 0.16
FRONTIER_FALLBACK_DIRECT_MAX_DIST_M = 1.55
# Step 1 — frontier reachability filter.  The fallback target chooser runs only
# when the wavefront planner found NO route.  It could still commit
# coverage_goal_map to a frontier with no direct route (direct_ok False), so the
# robot fixated on an unreachable frontier and looped scan/grid-realign forever
# with cov frozen.  In fallback, "no wavefront route AND no clear direct line" =
# unreachable now: do not commit it — blacklist it briefly so the next planner
# cycle picks a different, reachable frontier.  Toggle off to restore old fixate.
FRONTIER_REACHABILITY_FILTER_ENABLED = True
FRONTIER_UNREACHABLE_BLACKLIST_SEC = 30.0
FRONTIER_UNREACHABLE_BLACKLIST_RADIUS_M = 0.40
ACTIVE_SCAN_AREA_MEMORY_ENABLED = True
ACTIVE_SCAN_AREA_TILE_M = 1.15
ACTIVE_SCAN_AREA_REPEAT_SUPPRESS_SEC = 300.0
ACTIVE_SCAN_AREA_MEMORY_MAX = 24
# Scan-abort loop breaker.  When GRID_REALIGN / recovery preempts a SCAN_AROUND
# before it completes, the tile is otherwise never remembered (remember_active_
# scan_area runs only on finish), so the same scan restarts in place:
#   scan=start -> dwell 2/4 -> GRID_REALIGN -> scan=start  (deadlock, pose fixed)
# On abort: mark the tile, hard-suppress it briefly (completion-priority does NOT
# bypass this, unlike the normal area cooldown), and after repeated aborts in the
# same tile blacklist the current target so the planner replans to another goal.
ACTIVE_SCAN_ABORT_LOOP_GUARD_ENABLED = True
ACTIVE_SCAN_ABORT_SUPPRESS_SEC = 28.0
ACTIVE_SCAN_ABORT_BLACKLIST_AFTER = 2
ACTIVE_SCAN_ABORT_BLACKLIST_SEC = 45.0
ACTIVE_SCAN_ABORT_BLACKLIST_RADIUS_M = 0.90
# No-gain scan suppression.  A completed scan that revealed essentially no new
# local unknown area is useless; but completion-priority would re-force it in the
# same tile (it bypasses the normal area cooldown), giving the scan<->hard-corner
# GRID_REALIGN loop with cov frozen and add=0.  When a finished scan's local
# unknown did not drop by at least MIN_UNKNOWN_DROP cells, hard-suppress the tile
# via the abort memory (completion CANNOT bypass that), and after repeats
# blacklist the frontier target so the planner moves elsewhere.
ACTIVE_SCAN_NOGAIN_SUPPRESS_ENABLED = True
ACTIVE_SCAN_NOGAIN_MIN_UNKNOWN_DROP = 40
# Global progress governor (anti-freeze).  One regime-independent rule that
# subsumes every stuck mode we have seen (scan loop, frontier-only hold,
# unreachable fixate, wall pin): they ALL share one signature -- robot pose AND
# coverage are frozen while a goal is held.  Detect that once and abandon the
# goal (blacklist its neighbourhood + force replan), regardless of nav_state,
# regime, or which narrow watchdog would otherwise apply.  Progress is the only
# currency: make progress or drop the goal.  After repeated freezes the map is
# effectively exhausted -> return to dock.
GLOBAL_PROGRESS_GOVERNOR_ENABLED = True
PROGRESS_GOV_POSE_EPS_M = 0.18
PROGRESS_GOV_COV_GAIN_PERCENT = 0.4
PROGRESS_GOV_STALL_SEC = 26.0
PROGRESS_GOV_BLACKLIST_SEC = 40.0
PROGRESS_GOV_BLACKLIST_RADIUS_M = 0.90
PROGRESS_GOV_MAX_ESCALATIONS_BEFORE_DOCK = 6
# Do NOT dock while the map is still open: if a large gray gap remains, the map
# is not a closed room yet, so repeated freezes mean "stuck here", not "map
# done".  Instead of docking, relocate: blacklist a wide area around the stuck
# goal and force the planner to a far region.  Dock only when the gray gap is
# small (map effectively closed) OR after this many relocation attempts failed
# (the remaining gray is genuinely unreachable).
PROGRESS_GOV_DOCK_MAX_GRAY_GAP_CELLS = 1800
PROGRESS_GOV_RELOCATE_BLACKLIST_RADIUS_M = 1.6
PROGRESS_GOV_RELOCATE_BLACKLIST_SEC = 90.0
PROGRESS_GOV_MAX_RELOCATIONS_BEFORE_DOCK = 4
ACTIVE_SCAN_MIN_FRONTIER_GAIN_CELLS = 120
ACTIVE_SCAN_MIN_UNKNOWN_GAIN_CELLS = 220
EXPLORE_LOCK_CLEANUP_TARGETS_ENABLED = True
EXPLORE_CLEANUP_UNLOCK_MIN_COVERAGE_PERCENT = 68.0
EXPLORE_CLEANUP_UNLOCK_MIN_TIME_SEC = 180.0
EXPLORE_CLEANUP_UNLOCK_MAX_FRONTIER_CELLS = 900
# Round 6m: ratio-branch disabled (was 0.030).  The unlock OR'd this ratio with the
# absolute MAX_FRONTIER_CELLS gate, but as the map grows the cleanable denominator
# inflates, so 3% = ~12.7k cells — the overnight run unlocked to uncleaned-chasing with
# fr=10396 (>>900) because ratio=0.0246<=0.030.  That made the robot spend ~64% of the
# run driving over already-mapped floor (coverage) instead of mapping frontiers.  With
# 0.0 the ratio branch is inert and unlock requires the absolute frontiers<=900 gate, so
# EXPAND_MAP stays frontier-first until frontiers are genuinely exhausted.
EXPLORE_CLEANUP_UNLOCK_MAX_FRONTIER_RATIO = 0.0
EXPLORATION_FRONTIER_ROUTING_ENABLED = True
EXPLORATION_ROUTE_CLEANED_TRANSIT_PENALTY = 0.0
EXPLORATION_ROUTE_RECENT_TRANSIT_PENALTY = 0.10
EXPLORATION_ROUTE_COST_PENALTY = 5.20
EXPLORATION_ROUTE_TURN_PENALTY = 3.25
EXPLORATION_ROUTE_LATERAL_PENALTY = 0.62
EXPLORATION_ROUTE_FORWARD_BONUS = 2.20
EXPLORATION_ROUTE_MAX_DETOUR_RATIO = 2.35
EXPLORATION_ROUTE_MAX_EXTRA_DETOUR_M = 0.55
LOCAL_FIRST_FRONTIER_ENABLED = True
LOCAL_FIRST_FRONTIER_NEAR_RADIUS_M = 2.65
LOCAL_FIRST_FRONTIER_MID_RADIUS_M = 4.10
LOCAL_FIRST_FRONTIER_CLOSE_BONUS = 23.0
LOCAL_FIRST_FRONTIER_MID_BONUS = 7.0
LOCAL_FIRST_FRONTIER_FAR_PENALTY = 18.0
LOCAL_FIRST_FRONTIER_ROUTE_COST_WEIGHT = 1.85
LOCAL_FIRST_FRONTIER_GRAY_BONUS_SCALE = 0.009
LOCAL_FIRST_FRONTIER_GRAY_BONUS_MAX = 10.0
LOCAL_FIRST_FRONTIER_MIN_LOCAL_CELLS = 14
LOCAL_FIRST_FRONTIER_RECENT_PENALTY_SCALE = 4.5
LOCAL_FIRST_FRONTIER_DEBUG_ENABLED = True
LOCAL_FIRST_FRONTIER_NEAR_EXISTS_FAR_EXTRA_PENALTY = 2.25
LOCAL_FIRST_FRONTIER_USE_ROUTE_COST_RADIUS = True
LOCAL_FIRST_FRONTIER_USEFUL_UNKNOWN_MULT = 10
FRONTIER_NOISE_FILTER_ENABLED = True
FRONTIER_NOISE_MIN_COMPONENT_CELLS = 10
FRONTIER_NOISE_MIN_CLEANABLE_EDGE_CELLS = 8
FRONTIER_NOISE_RAY_MIN_SPAN_PX = 18
FRONTIER_NOISE_RAY_MAX_AREA_PX = 360
FRONTIER_NOISE_RAY_MAX_DENSITY = 0.22
FRONTIER_NOISE_RAY_MAX_NARROW_PX = 5
FRONTIER_NOISE_OBS_SHADOW_RATIO = 1.15
FRONTIER_NOISE_LARGE_KEEP_CELLS = 260
KNOWN_MAP_COVERAGE_EVAL_DEFAULT = False
KNOWN_MAP_EVAL_FREE_LO = -3.80
KNOWN_MAP_EVAL_OCC_LO = 6.20
KNOWN_MAP_EVAL_WALL_THICKNESS_M = 0.115
KNOWN_MAP_EVAL_OBSTACLE_PADDING_M = 0.025
KNOWN_MAP_EVAL_STRUCTURAL_OCC = 4.50
KNOWN_MAP_EVAL_VISUAL_OCC = 1.20
KNOWN_MAP_EVAL_RESEED_EVERY_RESET = True
KNOWN_MAP_EVAL_KEY_TOGGLE_ENABLED = True
KNOWN_MAP_EVAL_FORCE_ROUTE_COMMIT = True
KNOWN_MAP_EVAL_STOP_IF_NO_ROUTE = True
KNOWN_MAP_EVAL_DISABLE_STICKY_TARGETS = True
KNOWN_MAP_EVAL_SWEEP_PRIORITY_ENABLED = True
KNOWN_MAP_EVAL_SWEEP_LANE_SPACING_M = 0.36
KNOWN_MAP_EVAL_SWEEP_LANE_PRIORITY_BONUS = 260.0
KNOWN_MAP_EVAL_SWEEP_DIRECTION_BONUS = 38.0
KNOWN_MAP_EVAL_SWEEP_ROUTE_COST_WEIGHT = 0.35
KNOWN_MAP_EVAL_SWEEP_MIN_FP_GAIN = 3
KNOWN_MAP_EVAL_ROUTE_MARGIN_M = 0.030
KNOWN_MAP_EVAL_STRIP_ROUTE_ENABLED = True
KNOWN_MAP_EVAL_STRIP_MIN_COARSE_GAIN = 2
KNOWN_MAP_EVAL_STRIP_MIN_TOTAL_GAIN = 8
KNOWN_MAP_EVAL_STRIP_EDGE_MARGIN_CELLS = 1
KNOWN_MAP_EVAL_STRIP_LANE_PRIORITY_BONUS = 1800.0
KNOWN_MAP_EVAL_STRIP_GAIN_BONUS = 0.32
KNOWN_MAP_EVAL_STRIP_ROUTE_COST_WEIGHT = 1.15
KNOWN_MAP_EVAL_STRIP_TURN_PENALTY = 42.0
KNOWN_MAP_EVAL_STRIP_CORNER_PENALTY = 12.0
KNOWN_MAP_EVAL_STRIP_MAX_ROUTE_COST_M = 12.0
KNOWN_MAP_EVAL_FULL_SWEEP_ROUTE_ENABLED = True
KNOWN_MAP_EVAL_FULL_SWEEP_MAX_ROUTE_COST_M = 240.0
KNOWN_MAP_EVAL_FULL_SWEEP_MAX_SEGMENTS = 96
KNOWN_MAP_EVAL_FULL_SWEEP_CONNECTOR_MAX_NODES = 12000
KNOWN_MAP_EVAL_ROUTE_PROGRESS_SNAP_WINDOW_M = 0.55
KNOWN_MAP_EVAL_ROUTE_TRACKING_ENABLED = True
KNOWN_MAP_EVAL_ROUTE_TRACKING_LATERAL_M = 0.045
KNOWN_MAP_EVAL_ROUTE_TRACKING_POINT_HEADING_ERR = math.radians(7.0)
KNOWN_MAP_EVAL_ROUTE_TRACKING_PIVOT_ERR = math.radians(22.0)
KNOWN_MAP_EVAL_ROUTE_TRACKING_STEER_ERR = math.radians(3.5)
KNOWN_MAP_EVAL_ROUTE_TRACKING_STEER_KP = 1.20
KNOWN_MAP_EVAL_ROUTE_TRACKING_STEER_MAX = 0.52
KNOWN_MAP_EVAL_FREEZE_PLANNER_DURING_COMMIT = True
KNOWN_MAP_EVAL_ACTIVE_METRICS_UPDATE_STEPS = 18
KNOWN_MAP_EVAL_EDGE_LANE_BIAS_ENABLED = True
KNOWN_MAP_EVAL_EDGE_LANE_MIN_TOTAL_GAIN = 3
KNOWN_MAP_EVAL_DOCK_END_BIAS_ENABLED = True
KNOWN_MAP_EVAL_DOCK_END_BIAS_WEIGHT = 0.45
KNOWN_MAP_EVAL_OPTIMIZED_SWEEP_ORDER_ENABLED = True
KNOWN_MAP_EVAL_OPTIMIZER_EXACT_MAX_SEGMENTS = 12
KNOWN_MAP_EVAL_OPTIMIZER_2OPT_PASSES = 7
KNOWN_MAP_EVAL_OPTIMIZER_CONNECTOR_DOCK_BIAS = 0.20
KNOWN_MAP_EVAL_OPTIMIZER_ROW_JUMP_PENALTY = 0.08
KNOWN_MAP_EVAL_ROUTE_HEADING_CORR_MAX = 0.16
KNOWN_MAP_EVAL_ROUTE_ACQUIRE_HEADING_CORR_MAX = 0.12
KNOWN_MAP_EVAL_ROUTE_STRICT_POINT_ACQUIRE = True
KNOWN_MAP_EVAL_ROUTE_ACQUIRE_SPEED = 1.65
KNOWN_MAP_EVAL_ROUTE_POINT_REACQUIRE_M = 0.075
KNOWN_MAP_EVAL_SWEEP_ADAPTIVE_LANE_DIRECTION = True
KNOWN_MAP_EVAL_ROUTE_GRID_STEP_PX = 10
KNOWN_MAP_EVAL_FULL_SWEEP_BUDGET_MARGIN_M = 1.50
KNOWN_MAP_EVAL_GLOBAL_ROUTE_WINDOW = True
KNOWN_MAP_EVAL_GLOBAL_ROUTE_PADDING_M = 0.45
KNOWN_MAP_EVAL_ROUTE_COMMIT_MAX_COST_M = 240.0
KNOWN_MAP_EVAL_ROUTE_BASE_MAX_AGE_SEC = 40.0
KNOWN_MAP_EVAL_ROUTE_SEC_PER_M = 32.0
KNOWN_MAP_EVAL_ROUTE_MAX_AGE_SEC = 7200.0
KNOWN_MAP_EVAL_STRIP_TOP_DEBUG_COUNT = 4
KNOWN_MAP_EVAL_PRIMARY_SWEEP_ONCE = True
KNOWN_MAP_EVAL_EARLY_END_SWEEP_ENABLED = True
KNOWN_MAP_EVAL_EARLY_END_SWEEP_MIN_PROGRESS_FRAC = 0.78
KNOWN_MAP_EVAL_RETURN_AFTER_PRIMARY_SWEEP_PERCENT = 86.0
KNOWN_MAP_EVAL_RETURN_AFTER_MOPUP_PERCENT = 90.0
KNOWN_MAP_EVAL_RESIDUAL_CLEANUP_MAX_COMMITS = 2
KNOWN_MAP_EVAL_RESIDUAL_CLEANUP_MAX_SEC = 80.0
KNOWN_MAP_EVAL_RESIDUAL_LARGEST_COMPONENT_FOR_RETURN_CELLS = 1150
KNOWN_MAP_EVAL_RESIDUAL_TOTAL_FOR_RETURN_CELLS = 6200
KNOWN_MAP_EVAL_RESIDUAL_BIG_COMPONENT_CELLS = 900
KNOWN_MAP_WBT_ROBOT_START_X = -4.12
KNOWN_MAP_WBT_ROBOT_START_Y = 2.75
KNOWN_MAP_ARENA_X_MIN_M = -0.38
KNOWN_MAP_ARENA_X_MAX_M = 8.62
KNOWN_MAP_ARENA_Y_MIN_M = -6.25
KNOWN_MAP_ARENA_Y_MAX_M = 0.75
RUNTIME_ARENA_GUARD_ENABLED = True
RUNTIME_ARENA_GUARD_MARGIN_M = 0.12
RUNTIME_ARENA_FRONT_PROBE_M = 0.42
RUNTIME_ARENA_GUARD_HOLD_SEC = 1.35
RUNTIME_ARENA_REPLAN_HOLD_SEC = 2.20
ODOM_ARENA_CLAMP_ENABLED = True
ODOM_ARENA_CLAMP_MARGIN_M = 0.10
ODOM_ARENA_CLAMP_HOLD_SEC = 2.50
EXPLORATION_ROUTE_GEOMETRY_STABILITY_ENABLED = True
EXPLORATION_ROUTE_FIRST_TURN_PENALTY = 9.0
EXPLORATION_ROUTE_CORNER_PENALTY = 1.85
EXPLORATION_ROUTE_EXTRA_CORNER_PENALTY = 2.75
EXPLORATION_ROUTE_MAX_SOFT_CORNERS = 3
EXPLORATION_FRONTIER_ROW_PRIMARY_ENABLED = True
EXPLORATION_FRONTIER_ROW_PRIMARY_FRONT_CLEAR_M = 0.42
EXPLORATION_FRONTIER_ROW_PRIMARY_MAX_FIRST_TURN_FRAC = 0.45  # Round 6p: 0.24->0.45 so a side/interior frontier wins over plowing the row
EXPLORATION_FRONTIER_ROW_PRIMARY_MAX_CORNERS = 3
# Frontier exploration motion mode.
#   True  = pure-pursuit: continuously steer toward the next waypoint (smooth arcs
#           => wobbly, curved tracks; this was the main "dergonoe" motion source).
#   False = Manhattan segment follow: align once to the 4-connected route's cardinal
#           heading, drive straight, pivot in place only at real corners.
# The route planner is 4-connected, so False yields clean straight lines + 90deg
# turns for the whole mapping traversal. Set True to restore the legacy wobble (A/B).
EXPLORATION_FRONTIER_POINT_PURSUIT_ENABLED = False
EXPLORATION_FRONTIER_PIVOT_ERR = math.radians(42.0)
EXPLORATION_FRONTIER_STEER_ERR = math.radians(7.5)
EXPLORATION_FRONTIER_STEER_KP = 1.55
EXPLORATION_FRONTIER_STEER_MAX = 0.58
EXPLORATION_FRONTIER_PURSUIT_SPEED = 1.72
EXPLORATION_FRONTIER_PURSUIT_SLOW_SPEED = 0.92
FRONTIER_COMMIT_MIN_TRANSLATION_M = 0.45
FRONTIER_COMMIT_CLOSE_SIDE_TURN_FRAC = 0.22
RGBD_OCCLUSION_GUARD_ENABLED = True
RGBD_OCCLUSION_START_SKIP_CELLS = 3
RGBD_OCCLUSION_ENDPOINT_IGNORE_CELLS = 3
RGBD_OCCLUSION_LOG_EPS = 1.62
RGBD_OCCLUSION_STRUCT_EPS = 1.0
RGBD_OCCLUSION_CONTACT_EPS = 0.72
RGBD_OCCLUSION_VISUAL_EPS = 2.15
RGBD_OCCLUSION_HARD_LOG_EPS = 3.25
RGBD_OCCLUSION_SOFT_RUN_CELLS = 4
RGBD_OCCLUSION_SOFT_DENSE_COUNT = 4
RGBD_OCCLUSION_SOFT_DENSE_RADIUS = 1
MAP_VIEW_W = 860
MAP_VIEW_H = 620
MAP_VIEW_ZOOM_MIN = 0.50
MAP_VIEW_ZOOM_MAX = 3.00
MAP_VIEW_ZOOM_STEP = 1.25
MAP_VIEW_PAN_STEP_PX = 70
WHEEL_RADIUS = 0.055
WHEEL_BASE = 0.250
LEFT_SIGN = 1.0
RIGHT_SIGN = 1.0
ODOM_LEFT_SIGN = 1.0
ODOM_RIGHT_SIGN = 1.0
MAP_SIZE = 1000
MAP_SCALE = 85.0
MAP_ORIGIN_X = 180
MAP_ORIGIN_Y = 430
DEBUG_ARENA_BOUNDS_ENABLED = True
DEBUG_ARENA_X_MIN_M = KNOWN_MAP_ARENA_X_MIN_M
DEBUG_ARENA_X_MAX_M = KNOWN_MAP_ARENA_X_MAX_M
DEBUG_ARENA_Y_MIN_M = KNOWN_MAP_ARENA_Y_MIN_M
DEBUG_ARENA_Y_MAX_M = KNOWN_MAP_ARENA_Y_MAX_M
DEBUG_ARENA_CROP_MARGIN_M = 0.28
DEBUG_ARENA_BOUNDS_COLOR = (130, 130, 130)
LO_UNKNOWN_EPS = 0.18
LO_OCCUPIED_EPS = 2.25
RAW_MAP_SPECKLE_CLEANUP_ENABLED = True
RAW_MAP_SPECKLE_CLEANUP_STEPS = 6
RAW_MAP_SPECKLE_MIN_AREA_PX = 62
RAW_MAP_SPECKLE_MIN_SPAN_PX = 14
RAW_MAP_SPECKLE_KEEP_STRONG_MARGIN = 1.35
RAW_MAP_SPECKLE_DECAY_TO = -0.08
RAW_MAP_RAY_STREAK_CLEANUP_ENABLED = True
RAW_MAP_RAY_STREAK_MIN_SPAN_PX = 18
RAW_MAP_RAY_STREAK_MAX_AREA_PX = 420
RAW_MAP_RAY_STREAK_MAX_DENSITY = 0.24
RAW_MAP_RAY_STREAK_MAX_NARROW_PX = 7
RAW_MAP_RAY_STREAK_WALL_PROTECT_SPAN_PX = 90
LO_FREE_UPDATE = -0.24
LO_OCC_UPDATE = 0.80
LO_MIN = -5.0
LO_MAX = 7.0
CONTACT_OCCUPIED_EPS = 1.0
CONTACT_OCC_UPDATE = 2.7
CONTACT_FREE_UPDATE = -0.38
# Protect bumper-confirmed contact from being erased by depth that cannot see
# LOW objects (e.g. the 10 cm red box sits below the forward camera FOV, so the
# depth ray passes over it and reports "free").  While the contact is still
# strongly confirmed, depth clears it much more slowly, so a low object the robot
# physically hit stays on the map long enough for the planner to route around it
# instead of driving back into it.  It can still be cleared once it has decayed.
CONTACT_DEPTH_CLEAR_PROTECT_ENABLED = False
CONTACT_DEPTH_CLEAR_PROTECT_EPS = 1.0
CONTACT_DEPTH_CLEAR_PROTECT_FACTOR = 0.22
CONTACT_MIN = 0.0
CONTACT_MAX = 5.2
CONTACT_MARK_RADIUS_M = 0.035
CONTACT_FRONT_OFFSET_M = 0.215
CONTACT_SIDE_FORWARD_OFFSET_M = 0.166
CONTACT_SIDE_LATERAL_OFFSET_M = 0.098
CONTACT_LATCH_VALID_SEC = 0.45
CONTACT_COLOR = (0, 190, 255)
HYPOTHESIS_OBSTACLE_COLOR = (0, 135, 255)
HYPOTHESIS_EDGE_COLOR = (0, 95, 220)
MAX_VALID_RANGE = 5.7
MIN_VALID_RANGE = 0.035
OBSTACLE_RANGE_MARGIN = 0.12
FREE_STEP = 0.045
RAY_STRIDE = 4
RAY_EDGE_SKIP = 34
THIN_EDGE_SKIP = 6
NO_HIT_FREE_RANGE = 0.35
TURN_MAPPING_OMEGA_LIMIT = 0.12
TURN_THIN_OMEGA_LIMIT = 0.10
TURN_FREEZE_HOLD_SEC = 0.25
# Forward-arc mapping exception: the omega freeze above exists to kill depth
# "fan" artifacts from near-stationary pivots (TURN_IN_PLACE / FINE_ALIGN), where
# the robot rotates without translating and rays spread from one point.  But the
# heading-lock corrects course with a differential arc (base±corr), so even a
# straight drive trips the omega limit and freezes mapping unnecessarily.  A
# smooth forward arc (large turn radius R=v/omega while translating) changes
# heading only a fraction of a degree per map frame and is safe to map.  Keep
# mapping when driving forward with a large enough arc radius; set ENABLED False
# to restore the strict freeze.
FORWARD_ARC_MAPPING_ENABLED = True
FORWARD_ARC_MAPPING_MIN_LINEAR_MPS = 0.08
FORWARD_ARC_MAPPING_MIN_RADIUS_M = 0.40
TURN_OCC_MAX_RANGE = 0.70
TURN_FREE_MAX_RANGE = 0.00
DEPTH_JUMP_REJECT = 0.20
DEPTH_LOCAL_WINDOW = 7
MIN_VALID_COLUMN_SAMPLES = 3
SENSOR_OFFSET_X = 0.215
SENSOR_OFFSET_Y = 0.0
ROBOT_BODY_RADIUS = 0.18
BODY_ENVELOPE_MARGIN = 0.014
BODY_CORRIDOR_ROW_FRACTION = (0.32, 0.66)
BODY_CORRIDOR_VALID_MIN = 0.10
BODY_CORRIDOR_PASS_CLEARANCE = 0.105
BODY_CORRIDOR_HARD_CLEARANCE = 0.042
FOOTPRINT_PREDICTION_ENABLED = True
FOOTPRINT_RADIUS_M = ROBOT_BODY_RADIUS
FOOTPRINT_PASS_MARGIN_M = 0.004
FOOTPRINT_ROUTE_MARGIN_M = 0.000
FOOTPRINT_MAX_RAW_OBS_RATIO = 0.018
FOOTPRINT_MAX_CONTACT_RATIO = 0.002
FOOTPRINT_MIN_KNOWN_FREE_RATIO = 0.18
FOOTPRINT_SWEEP_STEP_M = 0.07
FOOTPRINT_ROUTE_DRAW_STRIDE = 2
FOOTPRINT_COLOR = (255, 120, 80)
FOOTPRINT_OK_COLOR = (80, 200, 80)
FOOTPRINT_BAD_COLOR = (70, 70, 255)
IMAGE_RIGHT_TO_ROBOT_Y_SIGN = -1.0
DEPTH_ROWS_FRACTION = (0.26, 0.50)
LOW_THIN_ROWS_FRACTION = (0.30, 0.94)
THIN_OBSTACLE_MAX_DIST = 1.75
THIN_OBSTACLE_TURN_MAX_DIST = 0.62
THIN_OBSTACLE_MIN_WIDTH = 1
THIN_OBSTACLE_MAX_WIDTH = 44
THIN_OBSTACLE_OCC_UPDATE = 1.55
THIN_OBSTACLE_MIN_COLUMN_SAMPLES = 1
THIN_OBSTACLE_CONFIRM_ENABLED = True
THIN_OBSTACLE_CONFIRM_UPDATE = 1.35
THIN_OBSTACLE_CONFIRM_EPS = 1.45
THIN_OBSTACLE_CONFIRM_DECAY = 0.96
THIN_OBSTACLE_CONFIRM_RADIUS = 3
CV_FUSION_ENABLED = True
CV_FEATURE_MAX_RANGE = 4.2
CV_FEATURE_MIN_RANGE = 0.10
CV_LINE_MIN_LENGTH = 32
CV_LINE_MAX_COUNT = 36
CV_CONTOUR_MIN_AREA = 130
CV_CONTOUR_MAX_FRAC = 0.50
CV_BOX_MAX_COUNT = 10
CV_DEPTH_PATCH = 2
CV_VISUAL_UPDATE = 1.15
CV_VISUAL_LINE_UPDATE = 1.05
CV_OCCUPANCY_SUPPORT_UPDATE = 0.28
CV_OCCUPIED_EPS = 0.78
CV_FREE_RAY_UPDATE = -0.08
CV_FREE_RAY_MAX_RANGE = 2.6
CV_FLOOR_Y_FRACTION = 0.44
CV_FLOOR_HORIZ_ANGLE_DEG = 14.0
CV_FLAT_FLOOR_LINE_MIN_LENGTH = 42
CV_WIDE_LOW_CONTOUR_FRAC = 0.12
CV_LOW_STRIP_MAX_HEIGHT_FRAC = 0.22
CV_LINE_SAMPLE_STEP_PX = 18
CV_LINE_MAX_DEPTH_SPAN_M = 0.55
CV_LINE_MAX_DEPTH_STD_M = 0.24
# Connecting projected line endpoints with a filled segment is the main source
# of the diagonal "fan" false-occupied streaks: when depth along the RGB line is
# noisy, the sampled points project into a spreading fan, and the bresenham fill
# turns that fan into solid diagonal strokes.  Only connect when the intermediate
# projected points actually lie on the straight p0->p1 line (a real wall edge);
# otherwise leave isolated dots that speckle/ray-streak cleanup can remove.
CV_LINE_CONNECT_MAX_MAP_PX = 80
CV_LINE_CONNECT_REQUIRE_COLLINEAR = True
CV_LINE_CONNECT_MAX_PERP_DEV_M = 0.05
# Height filter for CV obstacle features: the robot is ~0.12 m tall and only
# collides with floor-level structure (legs, low furniture).  A chair backrest,
# seat, or table top is ABOVE the robot — projecting those RGB-D features onto
# the 2D map turns the whole piece into a smeared obstacle instead of clean
# legs.  Estimate each feature's world height from its image row + depth and
# skip the obstacle contribution above this height (free-space rays still pass).
# Sensor height matches the .wbt camera translation (0.215 0 0.06).
CV_HEIGHT_FILTER_ENABLED = True
CV_SENSOR_HEIGHT_M = 0.06
CV_MAX_OBSTACLE_HEIGHT_M = 0.18
CV_FLOOR_PLANE_REJECT_ENABLED = True
CV_FLOOR_PLANE_MIN_Y_FRACTION = 0.34
CV_FLOOR_PLANE_MIN_DEPTH = 0.28
CV_FLOOR_PLANE_MAX_STD = 0.075
CV_FLOOR_PLANE_WIDE_FRAC = 0.08
CV_FLOOR_PLANE_MAX_BOX_HEIGHT_FRAC = 0.34
CV_SHADOW_FILTER_ENABLED = True
CV_SHADOW_LOW_VALUE = 118
CV_SHADOW_LOW_SATURATION = 95
CV_SHADOW_MIN_Y_FRACTION = 0.28
CV_SHADOW_OPEN_DEPTH_MIN = 0.65
CV_SHADOW_MAX_DEPTH_STD = 0.18
CV_LAYER_COLOR = (210, 80, 190)
CV_LINE_COLOR = (80, 220, 255)
CV_BOX_COLOR = (80, 255, 80)
CV_FIRST_MAPPING = True
DEPTH_SAFETY_CENTER_FRACTION = 0.24
DEPTH_SAFETY_RAY_STRIDE = 6
DEPTH_SAFETY_FREE_RANGE = 0.56
DEPTH_SAFETY_OCC_RANGE = 0.28
DEPTH_SAFETY_FREE_UPDATE = -0.10
DEPTH_SAFETY_OCC_UPDATE = 0.22
CV_VISIBILITY_FREE_WEDGE_ENABLED = True
CV_VISIBILITY_EDGE_SKIP = 10
CV_VISIBILITY_RAY_STRIDE = 3
CV_VISIBILITY_FREE_RANGE = 2.55
CV_VISIBILITY_NO_HIT_RANGE = 1.85
CV_VISIBILITY_HIT_MARGIN = 0.12
CV_VISIBILITY_FREE_UPDATE = -0.045
CV_VISIBILITY_MAX_OCC_TO_CLEAR = CV_OCCUPIED_EPS * 0.85
CV_NAV_BLOCK_DISTANCE = 0.52
CV_NAV_SIDE_DISTANCE = 0.30
STRUCTURAL_OBSTACLE_MEMORY_ENABLED = True
STRUCTURAL_OCCUPIED_EPS = 1.0
STRUCTURAL_VISUAL_PROMOTE_EPS = 2.15
STRUCTURAL_LOG_PROMOTE_EPS = LO_OCCUPIED_EPS + 0.45
STRUCTURAL_CONTACT_PROMOTE_EPS = CONTACT_OCCUPIED_EPS
STRUCTURAL_OCC_UPDATE = 0.72
STRUCTURAL_CONTACT_UPDATE = 2.2
STRUCTURAL_FREE_DECAY = -0.018
STRUCTURAL_STRONG_FREE_LO = -3.20
STRUCTURAL_MIN = 0.0
STRUCTURAL_MAX = 5.8
SAFE_FRONT_DISTANCE = 0.18
SLOW_FRONT_DISTANCE = 0.30
SIDE_DISTANCE = 0.18
CRUISE_SPEED = 4.2
SLOW_SPEED = 2.05
TURN_SPEED = 3.2
MAX_SPEED = 8.0
CMD_SMOOTH_ALPHA = 0.26
TURN_CMD_SMOOTH_ALPHA = 0.70
NAV_FORWARD = "FORWARD"
NAV_TURN_90 = "TURN_90_IN_PLACE"
NAV_SETTLE = "TURN_SETTLE"
NAV_LANE_SHIFT = "LANE_SHIFT"
NAV_RECOVERY_BACKUP = "RECOVERY_BACKUP"
NAV_LEG_ESCAPE_BACKUP = "LEG_ESCAPE_BACKUP"
NAV_LEG_ESCAPE_TURN = "LEG_ESCAPE_TURN"
NAV_LEG_ESCAPE_FORWARD = "LEG_ESCAPE_FORWARD"
NAV_LEG_PASS_TURN = "LEG_PASS_TURN"
NAV_LEG_PASS_FORWARD = "LEG_PASS_FORWARD"
NAV_LEG_PASS_ALIGN = "LEG_PASS_ALIGN"
NAV_PRE_PIVOT_BACKUP = "PRE_PIVOT_BACKUP"
NAV_GRID_REALIGN = "GRID_REALIGN"
NAV_SCAN_AROUND = "SCAN_AROUND"
NAV_RGBD_SNAPSHOT = "RGBD_SNAPSHOT"
NAV_CONTACT_BACKUP = "CONTACT_BACKUP"
NAV_CONTACT_WAIT_CLEAR = "CONTACT_WAIT_CLEAR"
NAV_CONTACT_ROTATE = "CONTACT_ROTATE"
NAV_CONTACT_FORWARD = "CONTACT_FORWARD"
CONTACT_RECOVERY_STATES = (
    NAV_CONTACT_BACKUP,
    NAV_CONTACT_WAIT_CLEAR,
    NAV_CONTACT_ROTATE,
    NAV_CONTACT_FORWARD,
)
# Quantitative experiment metrics (diploma report).  Ported from the main-folder
# experiment branch: writes *_timeseries.csv / *_events.csv / *_summary.json into
# the metrics/ dir; analyse with tools/analyze_metrics.py.  Press M to export.
METRICS_ENABLED = True
METRICS_DIR_NAME = "metrics"
METRICS_SAMPLE_PERIOD_SEC = 1.0
METRICS_HEAVY_SAMPLE_PERIOD_SEC = 5.0
METRICS_EXPORT_ON_SAVE = True
METRICS_KEY_EXPORT_ENABLED = True
# Periodic auto-export of summary.json while running (no keypress needed) so an
# up-to-date aggregate survives an abrupt Webots kill.  timeseries.csv is written
# continuously regardless.
METRICS_SUMMARY_AUTOEXPORT_SEC = 20.0

# Ground-truth obstacle-map metrics (false-occupied / false-free cell ratios).
# Built from the .wbt world geometry and compared against the learned obstacle
# mask.  Requires the metrics GPS for world<->map alignment; silently disabled if
# absent.  Evaluation-only; never used by navigation.
GROUND_TRUTH_METRICS_ENABLED = True
GROUND_TRUTH_ROBOT_HEIGHT_M = 0.12
GROUND_TRUTH_FLOOR_EPS_M = 0.02
GROUND_TRUTH_WALL_THICKNESS_M = 0.06
# Match tolerance for obstacle-map comparison: the learned map is rarely aligned
# to the .wbt geometry to the exact cell (depth/odometry noise + finite map
# resolution put an obstacle a few cells off the true edge).  A robot obstacle
# within this distance of a real one counts as correct (grey), instead of being
# scored as false-occupied/missed.  ~0.06 m ≈ 5 px at MAP_SCALE=85.  Set 0 for
# strict cell-exact scoring.
GROUND_TRUTH_MATCH_TOLERANCE_M = 0.06

MAPPING_ALLOWED_STATES = (NAV_FORWARD, NAV_LANE_SHIFT, NAV_LEG_PASS_FORWARD, NAV_CONTACT_FORWARD, NAV_SCAN_AROUND, NAV_RGBD_SNAPSHOT)
MAPPING_FREEZE_STATES = (
    NAV_TURN_90, NAV_SETTLE, NAV_RECOVERY_BACKUP,
    NAV_LEG_ESCAPE_BACKUP, NAV_LEG_ESCAPE_TURN, NAV_LEG_PASS_TURN, NAV_LEG_PASS_ALIGN,
    NAV_PRE_PIVOT_BACKUP, NAV_GRID_REALIGN,
    NAV_CONTACT_BACKUP, NAV_CONTACT_WAIT_CLEAR, NAV_CONTACT_ROTATE,
)
LANE_SPACING = 0.31
LANE_SHIFT_SPEED = 1.85
LANE_SHIFT_TIMEOUT_SEC = 3.8
LANE_SHIFT_HEADING_KP = 0.35
LANE_SHIFT_MAX_CORRECTION = 0.045
LANE_SHIFT_HEADING_DEADBAND = math.radians(2.5)
BACKUP_DISTANCE = 0.12
BACKUP_SPEED = 1.20
BACKUP_TIMEOUT_SEC = 0.65
ROW_TURN_COOLDOWN_SEC = 1.0
COVERAGE_RADIUS_M = 0.205
UNDER_SURFACE_STRICT_CLEANING = True
UNDER_SURFACE_CLEAN_RADIUS_M = 0.150
UNDER_SURFACE_CLEAN_FRONT_PROBE_M = 0.10
COVERAGE_SIDE_SAMPLES = 11
SIMPLE_SWEEP_FSM_ENABLED = False
SIMPLE_SWEEP_OWNER = "EXPLORE_SWEEP_FSM"
SIMPLE_SWEEP_FINISH_COVERAGE_PERCENT = 90.0
SIMPLE_SWEEP_MAX_LANES = 42
SIMPLE_SWEEP_SPEED = 2.05
SIMPLE_SWEEP_SLOW_SPEED = 0.95
SIMPLE_SWEEP_PRECONTACT_FRONT_M = 0.30
SIMPLE_SWEEP_PRECONTACT_CENTER_M = 0.28
SIMPLE_SWEEP_BACKUP_DISTANCE_M = 0.13
SIMPLE_SWEEP_BACKUP_TIMEOUT_SEC = 0.85
SIMPLE_SWEEP_LANE_SHIFT_M = LANE_SPACING
SIMPLE_SWEEP_LANE_SHIFT_SPEED = 1.25
SIMPLE_SWEEP_LANE_SHIFT_TIMEOUT_SEC = 4.2
SIMPLE_SWEEP_SIDE_HIT_EARLY_M = 0.11
SIMPLE_SWEEP_ESCAPE_FORWARD_M = 0.34
SIMPLE_SWEEP_ESCAPE_FORWARD_TIMEOUT_SEC = 1.8
SIMPLE_SWEEP_PRESERVE_AXIS_AFTER_ESCAPE = True
SIMPLE_SWEEP_REJOIN_ALIGN_AFTER_ESCAPE = True
SIMPLE_SWEEP_OWNER_MIN_SEC = 0.28
SIMPLE_SWEEP_OWNER_MIN_DIST_M = 0.025
SIMPLE_SWEEP_PIVOT_TIMEOUT_SEC = 3.0
SIMPLE_SWEEP_PIVOT_TIMEOUT_ACCEPT_RAD = math.radians(22.0)
SIMPLE_SWEEP_TURN_SETTLE_SEC = 0.70
SIMPLE_SWEEP_ALIGN_ENABLED = True
SIMPLE_SWEEP_ALIGN_TOL_RAD = math.radians(0.85)
SIMPLE_SWEEP_ALIGN_TIMEOUT_ACCEPT_RAD = math.radians(5.5)
SIMPLE_SWEEP_ALIGN_TIMEOUT_SEC = 1.8
SIMPLE_SWEEP_ALIGN_HARD_TIMEOUT_SEC = 3.2
SIMPLE_SWEEP_ALIGN_SETTLE_SEC = 0.16
SIMPLE_SWEEP_ALIGN_KP = 2.10
SIMPLE_SWEEP_ALIGN_MIN_SPEED = 0.46
SIMPLE_SWEEP_ALIGN_MAX_SPEED = 1.18
SIMPLE_SWEEP_STRAIGHT_REALIGN_RAD = math.radians(2.0)
SIMPLE_SWEEP_STRAIGHT_REALIGN_MIN_DIST_M = 0.18
SIMPLE_SWEEP_ALIGN_COOLDOWN_SEC = 0.45
SIMPLE_SWEEP_DEBUG_PREFIX = "exploreSweep"
SIMPLE_SWEEP_ARENA_SIDE_PICK_ENABLED = True
SIMPLE_SWEEP_ARENA_SIDE_PICK_MARGIN_M = 0.25
SIMPLE_SWEEP_MIN_LATERAL_PROGRESS_M = 0.20
SIMPLE_SWEEP_REPEAT_LANE_EPS_M = 0.16
SIMPLE_SWEEP_MAX_EXTRA_SHIFT_RETRIES = 2
SIMPLE_SWEEP_LANE_TARGET_MEMORY_ENABLED = True
SIMPLE_SWEEP_LANE_TARGET_TOL_M = 0.045
SIMPLE_SWEEP_LANE_TARGET_REPEAT_EPS_M = 0.12
SIMPLE_SWEEP_SHIFT_WRONG_WAY_M = 0.10
SIMPLE_SWEEP_LANE_SHIFT_MAX_DIST_M = max(0.70, LANE_SPACING * 1.65)
SIMPLE_SWEEP_STRAIGHT_HEADING_KP = 1.05
SIMPLE_SWEEP_STRAIGHT_MAX_CORRECTION = 0.10
SIMPLE_SWEEP_SHIFT_HEADING_KP = 1.20
SIMPLE_SWEEP_SHIFT_MAX_CORRECTION = 0.13
SIMPLE_SWEEP_LOCAL_CHURN_RADIUS_M = 0.22
SIMPLE_SWEEP_LOCAL_CHURN_WINDOW_SEC = 28.0
SIMPLE_SWEEP_LOCAL_CHURN_MAX_ACTIONS = 5
SIMPLE_SWEEP_FRONTIER_HANDOFF_ENABLED = True
SIMPLE_SWEEP_FRONTIER_HANDOFF_MIN_COVERAGE = 32.0
SIMPLE_SWEEP_FRONTIER_HANDOFF_STALL_SEC = 75.0
SIMPLE_SWEEP_FRONTIER_HANDOFF_MIN_FRONTIERS = 3000
SIMPLE_SWEEP_FRONTIER_HANDOFF_MIN_GAIN = 0.45
SIMPLE_SWEEP_FRONTIER_HANDOFF_EARLY_MIN_COVERAGE = 22.0
SIMPLE_SWEEP_FRONTIER_HANDOFF_EARLY_STALL_SEC = 35.0
SIMPLE_SWEEP_FRONTIER_HANDOFF_SHORT_ROUTE_M = 0.85
SIMPLE_SWEEP_LANE_SCORE_ENABLED = True
SIMPLE_SWEEP_LANE_SCORE_LOOKAHEAD = 8
SIMPLE_SWEEP_LANE_SCORE_HALF_WIDTH_M = max(0.11, COVERAGE_RADIUS_M * 0.70)
SIMPLE_SWEEP_LANE_SCORE_ROI_PAD_M = 0.85
SIMPLE_SWEEP_LANE_SCORE_SAMPLE_STEP = 3
SIMPLE_SWEEP_LANE_SCORE_MIN_POTENTIAL = 18.0
SIMPLE_SWEEP_LANE_SCORE_UNKNOWN_WEIGHT = 0.32
SIMPLE_SWEEP_LANE_SCORE_RECENT_WEIGHT = 0.45
SIMPLE_SWEEP_LANE_SCORE_CLEANED_WEIGHT = 0.55
SIMPLE_SWEEP_LANE_SCORE_MAX_REVISIT_RATIO = 0.78
SIMPLE_SWEEP_LANE_SCORE_MAX_OBSTACLE_RATIO = 0.48
SIMPLE_SWEEP_LANE_SCORE_SIDE_SWITCH_GAIN = 1.18
SIMPLE_SWEEP_LANE_SCORE_HISTORY_EPS_M = 0.17
SIMPLE_SWEEP_LANE_SCORE_FALLBACK_SKIP_LIMIT = 8
EXPLORE_SWEEP_INFO_GAIN_SELECTOR_ENABLED = True
EXPLORE_SWEEP_FRONTIER_UNKNOWN_WEIGHT = 1.35
EXPLORE_SWEEP_RAW_UNKNOWN_WEIGHT = 0.06
EXPLORE_SWEEP_UNCLEANED_FREE_WEIGHT = 0.72
EXPLORE_SWEEP_VISITED_LANE_PENALTY = 2.25
EXPLORE_SWEEP_RECENT_LANE_PENALTY = 1.35
EXPLORE_SWEEP_LANE_BAND_EPS_M = max(0.13, SIMPLE_SWEEP_LANE_SCORE_HALF_WIDTH_M * 1.25)
EXPLORE_SWEEP_LANE_HISTORY_LIMIT = 80
EXPLORE_SWEEP_MIN_FRONTIER_POTENTIAL = 10.0
EXPLORE_SWEEP_VIRTUAL_ROW_END_ENABLED = True
EXPLORE_SWEEP_VIRTUAL_ROW_END_MIN_ROW_M = 0.35
EXPLORE_SWEEP_VIRTUAL_FRONT_M = 0.075
EXPLORE_SWEEP_VIRTUAL_CENTER_M = 0.095
EXPLORE_SWEEP_VIRTUAL_UPPER_M = 0.115
EXPLORE_SWEEP_ARENA_FRONT_GUARD_ENABLED = True
EXPLORE_SWEEP_ARENA_FRONT_GUARD_MARGIN_M = 0.10
EXPLORE_SWEEP_ARENA_FRONT_PROBE_M = 0.23
FURNITURE_ZONE_DETECTION_ENABLED = True
FURNITURE_ZONE_UPDATE_STEPS = 12
FURNITURE_ZONE_CLOSE_M = 0.085
FURNITURE_ZONE_INFLATE_M = 0.080
FURNITURE_ZONE_MIN_AREA_PX = 20
FURNITURE_ZONE_MAX_AREA_PX = 2600
FURNITURE_ZONE_MAX_SPAN_M = 1.45
FURNITURE_ZONE_WALL_TOUCH_PAD_M = 0.20
FURNITURE_ZONE_MIN_DENSITY = 0.16
FURNITURE_ZONE_MIN_STRONG_SUPPORT = 6
FURNITURE_ZONE_MIN_SOURCE_TYPES = 2
FURNITURE_ZONE_MAX_ASPECT = 5.0
FURNITURE_ZONE_HARD_MAX_ASPECT = 8.0
FURNITURE_ZONE_DIAGONAL_FAN_MAX_ASPECT = 3.6
FURNITURE_ZONE_DIAGONAL_FAN_MIN_FILL = 0.20
FURNITURE_ZONE_CONTACT_ISLAND_EPS = 4.2
FURNITURE_ZONE_COLOR = (210, 70, 230)
FURNITURE_ZONE_INFLATED_COLOR = (170, 120, 190)
FURNITURE_ZONE_DRAW_OVERLAY = False
FURNITURE_ZONE_DRAW_LABELS = False
# Structural leg-quad fitting: detect small leg clusters, fit rectangles, snap
# missing legs into structural_log_odds for robust furniture footprints.
# Requires STRUCTURAL_OBSTACLE_MEMORY_ENABLED and FURNITURE_ZONE_DETECTION_ENABLED.
FURNITURE_LEG_QUAD_ENABLED = True
# Steps between full re-fits (25 ≈ 1.6 s at 64 ms timestep).
FURNITURE_LEG_QUAD_UPDATE_STEPS = 25
# Minimum detected leg candidates to attempt fitting.  Must be >=3: a rectangle
# cannot be reconstructed from 2 points without inventing phantom corners.
FURNITURE_LEG_QUAD_MIN_LEGS = 3
# How many rectangle corners may be reconstructed without a real leg candidate
# (the genuinely missing 4th leg).  Keep at 1 to avoid phantom furniture.
FURNITURE_LEG_QUAD_MAX_INFERRED_CORNERS = 1
# Connected-component size window for individual leg clusters (px).
FURNITURE_LEG_QUAD_MIN_LEG_PX = 3
FURNITURE_LEG_QUAD_MAX_LEG_PX = 90
# Max aspect ratio of a leg bounding box (legs are compact, not elongated).
FURNITURE_LEG_QUAD_LEG_MAX_ASPECT = 3.5
# Spatial grouping distance – legs of the same piece of furniture.
FURNITURE_LEG_QUAD_MAX_SPAN_M = 1.55
# Minimum rectangle side to accept (filters out point-cloud noise pairs).
FURNITURE_LEG_QUAD_MIN_SPAN_M = 0.28
# Expected furniture footprints (long_side, short_side) in metres, from the .wbt
# world: table legs span 1.1x0.7, chair legs ~0.5x0.5.  A fitted rectangle must
# match one of these within SIZE_TOL, otherwise it is a mix of legs from
# different pieces (e.g. 2 chair legs + 1 table leg) and is rejected.  Empty list
# disables the size gate (falls back to the broad MIN/MAX_SPAN only).
FURNITURE_LEG_QUAD_EXPECTED_SIZES_M = [(1.1, 0.7), (0.5, 0.5)]
FURNITURE_LEG_QUAD_SIZE_TOL_M = 0.13
# Snap tolerance expressed as a fraction of the longer bounding-box side.
FURNITURE_LEG_QUAD_SNAP_TOL_FRAC = 0.32
# Minimum fit quality [0, 1] required to stamp missing corners.
FURNITURE_LEG_QUAD_MIN_QUALITY = 0.54
# Radius of the disc stamped at each fitted corner (metres).
FURNITURE_LEG_QUAD_FILL_RADIUS_M = 0.055
# Log-odds added to structural_log_odds at each stamped corner cell.
FURNITURE_LEG_QUAD_PROMOTE_SCORE = 3.5
# Wall-line denoise: walls/large obstacles are mostly straight axis-aligned
# lines.  Short diagonal/perpendicular "spurs" that stick out of a detected
# wall line are RGB-D/depth ray noise, not real geometry.  This finds straight
# wall segments via HoughLinesP and decays small adjacent spur components.
# Conservative: never touches the wall body itself, nor contact/structural/
# furniture-confirmed cells.  Toggle off to disable entirely.
WALL_LINE_DENOISE_ENABLED = True
WALL_LINE_DENOISE_UPDATE_STEPS = 14
# A straight segment must be at least this long to count as a wall (metres).
WALL_LINE_MIN_LENGTH_M = 0.45
# Max pixel gap bridged when joining collinear segments (metres).
WALL_LINE_MAX_GAP_M = 0.12
# HoughLinesP accumulator vote threshold.
WALL_LINE_HOUGH_THRESHOLD = 26
# Only accept near-axis-aligned walls (rooms are rectangular); reject diagonals.
WALL_LINE_AXIS_ALIGNED_ONLY = True
WALL_LINE_ANGLE_TOL_DEG = 14.0
# Half-thickness of the protected wall body around each detected line (metres).
WALL_LINE_CORE_HALF_WIDTH_M = 0.05
# Band beyond the wall body where spurs are searched for (metres).
WALL_LINE_NEAR_BAND_M = 0.11
# A spur candidate must be small and short to be erased.
WALL_LINE_SPUR_MAX_AREA_PX = 40
WALL_LINE_SPUR_MAX_LENGTH_M = 0.30
# Shape gate: erase only elongated spurs (high bbox aspect), sparse line-like
# stubs (low fill density — covers diagonals whose bbox looks square), or tiny
# specks.  Compact dense leg-sized clusters near a wall are protected.
WALL_LINE_SPUR_MIN_ASPECT = 2.2
WALL_LINE_SPUR_MAX_DENSITY = 0.45
WALL_LINE_SPUR_TINY_AREA_PX = 6
# Log-odds the erased spur cells are pulled down to.
WALL_LINE_DENOISE_DECAY_TO = -0.08
PLANNING_LAYER_ENABLED = True
PLANNING_CENTER_NO_GO_USES_FURNITURE_INFLATION = True
PLANNING_CENTER_NO_GO_CLOSE_GAPS_M = 0.020
EDGE_TRIM_COVERAGE_ENABLED = True
EDGE_TRIM_EXTRA_M = 0.030
EDGE_TRIM_NEAR_OBSTACLE_M = 0.075
EDGE_TRIM_REQUIRE_KNOWN_FREE = True
EDGE_TRIM_MIN_FREE_LO = -0.04
EDGE_TRIM_CLEAN_UNDER_SURFACE = False
WALL_FRINGE_TRIM_ENABLED = True
WALL_FRINGE_NEAR_OBSTACLE_M = 0.055
WALL_FRINGE_NEAR_CLEANED_M = 0.135
WALL_FRINGE_UPDATE_STEPS = 5
WALL_FRINGE_MAX_MARK_PER_UPDATE = 1400
WALL_FRINGE_UNREACHABLE_BAND_M = 0.045
UNREACHABLE_TARGET_TRIM_ENABLED = True
UNREACHABLE_TARGET_TRIM_UPDATE_STEPS = 8
UNREACHABLE_TARGET_TRIM_NEAR_CLEANED_M = 0.24
UNREACHABLE_TARGET_TRIM_MAX_MARK = 1800
BUMPER_ACTIVE_THRESHOLD = 0.001
BUMPER_BACKUP_DISTANCE = 0.075
BUMPER_TURN_AWAY_DELAY_SEC = 0.15
BUMPER_VALID_FRONT_DISTANCE = 0.78
BUMPER_VALID_CENTER_DISTANCE = 0.78
WALL_GRAZE_DISTANCE = 0.065
WALL_GRAZE_FRONT_LIMIT = 0.24
BUMPER_IGNORE_REQUIRES_EXPLICIT_FLOOR_CV = True
BUMPER_RUG_IGNORE_MAX_HOLD_SEC = 0.025
BUMPER_RUG_IGNORE_MAX_CONTACT_CELLS = 2
SENSOR_STALL_ENABLED = True
SENSOR_STALL_MIN_SEC = 0.55
SENSOR_STALL_MIN_ROW_AGE_SEC = 0.90
SENSOR_STALL_DEPTH_DELTA = 0.020
SENSOR_STALL_RGB_DELTA = 2.5
SENSOR_STALL_CONTEXT_CV_HITS = 28
SENSOR_STALL_SIDE_CONTEXT_M = 0.095
SENSOR_STALL_BODY_CONTEXT_M = 0.055
SIDE_RISK_DISTANCE = 0.075
SIDE_RISK_BODY_CLEARANCE = 0.065
SIDE_RISK_LATERAL = 0.125
SIDE_RISK_COOLDOWN_SEC = 0.80
ODOM_STALL_ENABLED = True
ODOM_STALL_MIN_SEC = 0.60
ODOM_STALL_MIN_PROGRESS = 0.012
ODOM_STALL_CMD_MIN = 0.55
LEG_ESCAPE_FRONT_OPEN_DISTANCE = 0.50
LEG_ESCAPE_BACKUP_DISTANCE = 0.28
LEG_ESCAPE_BACKUP_SPEED = 1.20
LEG_ESCAPE_STRAIGHT_BACKUP = True
LEG_ESCAPE_REVERSE_TURN = 0.72
LEG_ESCAPE_BACKUP_TIMEOUT_SEC = 1.9
LEG_ESCAPE_TURN_ANGLE = math.radians(42.0)
LEG_ESCAPE_TURN_SPEED = 2.25
LEG_ESCAPE_TURN_KP = 2.3
LEG_ESCAPE_TURN_TOLERANCE = math.radians(2.0)
LEG_ESCAPE_FORWARD_DISTANCE = 0.58
LEG_ESCAPE_FORWARD_SPEED = 2.05
LEG_ESCAPE_FORWARD_TIMEOUT_SEC = 2.2
LEG_ESCAPE_COOLDOWN_SEC = 0.55
LEG_TRAP_EDGE_GRAZE_DISTANCE = 0.052
LEG_TRAP_BODY_CLEARANCE = 0.070
LEG_TRAP_BACKUP_DISTANCE = 0.20
LEG_TRAP_BACKUP_TIMEOUT_SEC = 1.20
LEG_TRAP_TURN_ANGLE = math.radians(78.0)
LEG_TRAP_FORWARD_DISTANCE = 0.30
LEG_TRAP_FORWARD_TIMEOUT_SEC = 2.0
LEG_TRAP_COOLDOWN_SEC = 1.0
FRONT_CONTACT_TRAP_BACKUP_DISTANCE = 0.060
FRONT_CONTACT_TRAP_BACKUP_TIMEOUT_SEC = 0.55
FRONT_CONTACT_TRAP_TURN_ANGLE = math.radians(90.0)
FRONT_CONTACT_TRAP_FORWARD_DISTANCE = 0.24
FRONT_CONTACT_TRAP_FORWARD_TIMEOUT_SEC = 1.35
UNDER_FURNITURE_TRAP_COOLDOWN_SEC = 8.0
CONTACT_RECOVERY_SUPPRESS_UNDER_SEC = 6.5
LOW_OBSTACLE_GUARD_ENABLED = True
LOW_OBSTACLE_GUARD_FRONT_M = 0.20
LOW_OBSTACLE_GUARD_CENTER_M = 0.14
LOW_OBSTACLE_GUARD_BODY_M = 0.034
LOW_OBSTACLE_GUARD_COOLDOWN_SEC = 0.75
LOW_OBSTACLE_GUARD_MAP_BUILDING_ENABLED = True
LOW_OBSTACLE_MEMORY_ENABLED = True
LOW_OBSTACLE_MEMORY_RADIUS_M = 0.060
LOW_OBSTACLE_MEMORY_SUPPORT_RADIUS_M = 0.035
LOW_OBSTACLE_MEMORY_FRONT_M = 0.235
LOW_OBSTACLE_MEMORY_MIN_FRONT_M = 0.135
LOW_OBSTACLE_MEMORY_UPDATE = 3.2
LOW_OBSTACLE_MEMORY_LO_UPDATE = 1.45
LOW_OBSTACLE_MEMORY_THIN_UPDATE = 1.10
LOW_OBSTACLE_MEMORY_COOLDOWN_SEC = 0.35
CONTACT_ESCAPE_VERIFY_SPEED = 1.20
TRAP_ESCAPE_VERIFY_SPEED = 1.35
UNDER_FURNITURE_CONFIRM_FRAMES = 4
UNDER_FURNITURE_MIN_AHEAD_CELLS = 4
UNDER_FURNITURE_STRICT_MIN_AHEAD_CELLS = 10
UNDER_FURNITURE_AHEAD_SCAN_M = 0.72
UNDER_FURNITURE_AHEAD_HALF_WIDTH_M = 0.17
CONTACT_ROUTE_KILL_SEC = 2.2
CONTACT_RECOVERY_ENABLED = True
CONTACT_CLEAR_STABLE_SEC = 0.22
CONTACT_WAIT_CLEAR_SEC = 0.10
CONTACT_BACKUP_EXTRA_TIMEOUT_SEC = 0.10
CONTACT_BACKUP_HOLD_SPEED = 0.18
CONTACT_ROTATE_TOLERANCE = math.radians(0.55)
CONTACT_ROTATE_KP = 2.25
CONTACT_ROTATE_MIN_SPEED = 0.58
CONTACT_ROTATE_MAX_SPEED = 2.65
CONTACT_FORWARD_DEFAULT_TIMEOUT_SEC = 1.35
CONTACT_RECOVERY_ROUTE_KILL_SEC = 2.8
CONTACT_RECOVERY_STABILIZE_DISTANCE_M = 0.10
CONTACT_RECOVERY_WALL_STABILIZE_DISTANCE_M = 0.12
CONTACT_RECOVERY_STABILIZE_SEC = 2.6
CONTACT_RECOVERY_WALL_STABILIZE_SEC = 2.2
NARROW_PASSAGE_CENTERING_ENABLED = True
NARROW_PASSAGE_MIN_FRONT_M = 0.36
NARROW_PASSAGE_MIN_CENTER_M = 0.30
NARROW_PASSAGE_MIN_UPPER_M = 0.38
NARROW_PASSAGE_SIDE_NEAR_M = 0.34
NARROW_PASSAGE_BODY_SOFT_M = BODY_CORRIDOR_PASS_CLEARANCE + 0.055
NARROW_PASSAGE_BODY_MIN_M = BODY_CORRIDOR_HARD_CLEARANCE + 0.018
NARROW_PASSAGE_LATERAL_DEADBAND_M = 0.020
NARROW_PASSAGE_LATERAL_KP = 5.2
NARROW_PASSAGE_SIDE_KP = 1.1
NARROW_PASSAGE_MAX_YAW = 0.78
NARROW_PASSAGE_MIN_YAW = 0.18
NARROW_PASSAGE_SPEED = 1.05
NARROW_PASSAGE_UNDER_SPEED = 0.82
NARROW_PASSAGE_MAX_SEC = 3.2
NARROW_PASSAGE_COOLDOWN_SEC = 0.00
GAP_MOUTH_ALIGN_ENABLED = True
GAP_MOUTH_FRONT_SOFT_M = 0.30
GAP_MOUTH_CENTER_SOFT_M = 0.34
GAP_MOUTH_UPPER_OPEN_M = 0.46
GAP_MOUTH_MIN_OPEN_SIDE_M = 0.42
GAP_MOUTH_SIDE_NEAR_M = 0.30
GAP_MOUTH_BODY_SOFT_M = BODY_CORRIDOR_PASS_CLEARANCE + 0.075
GAP_MOUTH_BODY_MIN_M = BODY_CORRIDOR_HARD_CLEARANCE + 0.012
GAP_MOUTH_ASYMMETRY_M = 0.065
GAP_MOUTH_SPEED = 0.78
GAP_MOUTH_SLOW_SPEED = 0.52
GAP_MOUTH_MAX_YAW = 0.62
GAP_MOUTH_MIN_YAW = 0.16
GAP_MOUTH_YAW_KP = 1.55
GAP_MOUTH_BODY_LAT_KP = 4.6
GAP_MOUTH_COOLDOWN_SEC = 0.00
GAP_MOUTH_HARD_STOP_FRONT_M = 0.075
GAP_MOUTH_HARD_STOP_CENTER_M = 0.105
WALL_HUG_ENABLED = True
WALL_HUG_SIDE_NEAR_M = 0.40
WALL_HUG_TARGET_CLEARANCE_M = 0.085
WALL_HUG_TOO_CLOSE_M = 0.040
WALL_HUG_ACQUIRED_SIDE_MAX_M = 0.18
WALL_HUG_REACQUIRE_SIDE_MAX_M = 0.24
WALL_HUG_TARGET_DEADBAND_M = 0.018
WALL_HUG_MIN_FRONT_M = 0.30
WALL_HUG_MIN_CENTER_M = 0.26
WALL_HUG_MIN_UPPER_M = 0.30
WALL_HUG_BODY_MIN_M = BODY_CORRIDOR_HARD_CLEARANCE + 0.006
WALL_HUG_KP = 1.05
WALL_HUG_MAX_YAW = 0.075
WALL_HUG_SPEED = 1.75
WALL_HUG_SLOW_SPEED = 1.05
WALL_HUG_SIDE_ASYMMETRY_M = 0.10
WALL_CONTACT_RECOVERY_ENABLED = True
WALL_CONTACT_FRONT_MAX_M = 0.46
WALL_CONTACT_CENTER_MAX_M = 0.48
WALL_CONTACT_UPPER_MAX_M = 0.62
WALL_CONTACT_SIDE_NEAR_M = 0.42
WALL_CONTACT_BACKUP_DISTANCE = 0.045
WALL_CONTACT_BACKUP_TIMEOUT_SEC = 0.38
WALL_CONTACT_TURN_ANGLE = math.radians(90.0)
WALL_CONTACT_FORWARD_DISTANCE = 0.62
WALL_CONTACT_FORWARD_TIMEOUT_SEC = 1.65
WALL_CONTACT_FORWARD_SPEED = 1.35
WALL_CONTACT_ROUTE_KILL_SEC = 0.75
REVERSE_BACKUP_GUARD_ENABLED = True
REVERSE_BACKUP_CHECK_STEP_M = 0.035
REVERSE_BACKUP_SHELL_MARGIN_M = 0.035
REVERSE_BACKUP_SIDE_FRAC = 0.78
REVERSE_BACKUP_STOP_CLEARANCE_M = 0.055
REVERSE_BACKUP_LOOKAHEAD_CAP_M = 0.42
CORNER_NUDGE_BACKUP_DISTANCE = 0.09
CORNER_NUDGE_BACKUP_TIMEOUT_SEC = 0.95
CORNER_NUDGE_TURN_ANGLE = math.radians(24.0)
CORNER_NUDGE_FORWARD_DISTANCE = 0.34
CORNER_NUDGE_FORWARD_TIMEOUT_SEC = 1.25
CORNER_NUDGE_FORWARD_SPEED = 0.66
POST_GAP_COMMIT_SEC = 1.65
POST_GAP_COMMIT_DISTANCE_M = 0.28
POST_GAP_COMMIT_SPEED = 0.72
GAP_CONTACT_NUDGE_ENABLED = True
GAP_CONTACT_NUDGE_BACKUP_DISTANCE = 0.075
GAP_CONTACT_NUDGE_BACKUP_TIMEOUT_SEC = 0.65
GAP_CONTACT_NUDGE_TURN_ANGLE = math.radians(20.0)
GAP_CONTACT_NUDGE_FORWARD_DISTANCE = 0.36
GAP_CONTACT_NUDGE_FORWARD_TIMEOUT_SEC = 1.55
GAP_CONTACT_NUDGE_FORWARD_SPEED = 0.62
CONTACT_CLUSTER_TIME_SEC = 5.5
CONTACT_CLUSTER_RADIUS_M = 0.30
CONTACT_CLUSTER_ROUTE_KILL_SEC = 4.2
CORNER_REPEAT_BACKUP_DISTANCE = 0.30
CORNER_REPEAT_BACKUP_TIMEOUT_SEC = 2.10
CORNER_REPEAT_TURN_ANGLE = math.radians(92.0)
CORNER_REPEAT_FORWARD_DISTANCE = 0.14
CORNER_REPEAT_FORWARD_TIMEOUT_SEC = 0.95
LEG_PASS_ENABLED = False
LEG_PASS_DETECT_DISTANCE = 0.56
LEG_PASS_SIDE_OPEN_DISTANCE = 0.38
LEG_PASS_MAX_WIDTH_FRAC = 0.34
LEG_PASS_TURN_ANGLE = math.radians(17.0)
LEG_PASS_TURN_SPEED = 1.85
LEG_PASS_TURN_KP = 2.5
LEG_PASS_TURN_TOLERANCE = math.radians(2.0)
LEG_PASS_FORWARD_DISTANCE = 0.48
LEG_PASS_FORWARD_SPEED = 1.85
LEG_PASS_FORWARD_TIMEOUT_SEC = 2.10
LEG_PASS_ALIGN_SPEED = 2.05
LEG_PASS_COOLDOWN_SEC = 0.55
LEG_PASS_FRONT_ABORT_DISTANCE = 0.075
LEG_PASS_AFTER_ALIGN_GRACE_SEC = 1.80
LEG_PASS_OPEN_SIDE_PROBE_DISTANCE = 0.42
UNDER_FURNITURE_ENABLED = False
UNDER_FURNITURE_FRONT_OPEN = 0.42
UNDER_FURNITURE_CENTER_OPEN = 0.52
UNDER_FURNITURE_UPPER_OPEN = 0.42
UNDER_FURNITURE_SIDE_NEAR = 0.72
UNDER_FURNITURE_HOLD_SEC = 1.55
UNDER_FURNITURE_SPEED = 1.35
UNDER_FURNITURE_OVERHEAD_NEAR_MAX = 1.85
UNDER_FURNITURE_STRICT_CV_DEPTH_HITS = 12
FOOTPRINT_FIRST_CLOSE_CONTACT = True
PASSAGE_MULTILANE_ENABLED = False
PASSAGE_MULTILANE_MIN_SIDE_OFFSET_M = 0.18
PASSAGE_MULTILANE_MAX_SIDE_OFFSET_M = 0.31
PASSAGE_MULTILANE_STEP_M = 0.055
PASSAGE_MULTILANE_FORWARD_MIN_M = 0.18
PASSAGE_MULTILANE_FORWARD_MAX_M = 0.82
PASSAGE_MULTILANE_FORWARD_STEP_M = 0.12
PASSAGE_MULTILANE_MIN_UNCLEANED_CELLS = 10
PASSAGE_MULTILANE_MAX_BLOCKED_RATIO = 0.18
PASSAGE_MULTILANE_COOLDOWN_SEC = 3.2
PASSAGE_MULTILANE_MAX_PER_OPENING = 1
PASSAGE_MULTILANE_SHIFT_SPEED = 2.15
PASSAGE_MULTILANE_MIN_COVERAGE_PERCENT = 38.0
PASSAGE_MULTILANE_MIN_ROW_PROGRESS_M = 1.15
PASSAGE_MULTILANE_MIN_UNDER_USEFUL_CELLS = 18
PASSAGE_MULTILANE_SPATIAL_COOLDOWN_M = 0.72
PASSAGE_MULTILANE_SPATIAL_COOLDOWN_SEC = 12.0
PASSAGE_MULTILANE_RESET_DISTANCE_M = 0.85
UNDER_SURFACE_ENABLED = False
UNDER_SURFACE_EPS = 0.85
UNDER_SURFACE_UPDATE = 1.05
UNDER_SURFACE_DECAY_ON_OBSTACLE = -1.8
UNDER_SURFACE_MIN_FRONT_OPEN = 0.44
UNDER_SURFACE_MARK_AHEAD_M = 0.72
UNDER_SURFACE_MARK_MIN_M = 0.24
UNDER_SURFACE_HALF_WIDTH_M = 0.205
UNDER_SURFACE_CELL_STEP_M = 0.085
UNDER_SURFACE_TARGET_BONUS = 9.0
UNDER_SURFACE_TARGET_MAX_DIST = 0.62
UNDER_SURFACE_TARGET_DISTANCE_PENALTY = 6.2
UNDER_SURFACE_OVERHEAD_MIN = 0.32
UNDER_SURFACE_OVERHEAD_MAX = 1.65
UNDER_SURFACE_MIN_CV_CONTEXT = 10
UNDER_SURFACE_MIN_DEPTH_CONTEXT = 7
UNDER_SURFACE_TARGET_LATERAL_LIMIT_M = 0.26
UNDER_SURFACE_TARGET_FORWARD_LIMIT_M = 0.62
UNDER_SURFACE_MAX_LATERAL_PER_FORWARD = 0.42
UNDER_SURFACE_LINE_CLEAR_OBSTACLE_RATIO = 0.04
UNDER_SURFACE_LINE_CLEAR_STEP_PX = 4
UNDER_SURFACE_DIRECT_LATERAL_TOL_M = 0.18
LOCAL_POCKET_FILL_ENABLED = False
LOCAL_POCKET_SCAN_AHEAD_M = 0.82
LOCAL_POCKET_SIDE_MIN_M = 0.20
LOCAL_POCKET_SIDE_MAX_M = 0.66
LOCAL_POCKET_AHEAD_STEP_M = 0.105
LOCAL_POCKET_SIDE_STEP_M = 0.085
LOCAL_POCKET_MIN_UNCLEANED_CELLS = 8
LOCAL_POCKET_MAX_OBSTACLE_RATIO = 0.16
LOCAL_POCKET_MIN_SCORE = 7.5
LOCAL_POCKET_SCORE_MARGIN = 1.7
LOCAL_POCKET_COOLDOWN_SEC = 2.6
LOCAL_POCKET_SHIFT_MIN_M = 0.20
LOCAL_POCKET_SHIFT_MAX_M = 0.50
LOCAL_POCKET_SHIFT_EXTRA_M = 0.06
LOCAL_POCKET_CLEAR_HALF_WIDTH_M = 0.14
LOCAL_POCKET_UNDER_FURNITURE_BONUS = 3.0
LOCAL_POCKET_CLEANED_AHEAD_TRIGGER = 0.36
LOCAL_POCKET_MAX_AHEAD_UNCLEANED_RATIO = 0.34
LOCAL_POCKET_MIN_CLEANED_AHEAD_RATIO = 0.44
LOCAL_POCKET_MIN_ROW_PROGRESS_M = 0.95
LOCAL_POCKET_OUTER_SIDE_MIN_M = 0.72
LOCAL_POCKET_OUTER_SIDE_MAX_M = 1.08
LOCAL_POCKET_MAX_OUTER_UNCLEANED_RATIO = 0.28
ROW_MAX_DISTANCE = 8.00
REVISIT_ROW_TIME_SEC = 15.0
REVISIT_CLEANED_RATIO = 0.95
REVISIT_FORCE_AFTER_SEC = 4.2
REVISIT_FORCE_MIN_DISTANCE = 0.65
REVISIT_FORCE_CLEANED_RATIO = 0.56
REVISIT_FORCE_MAX_UNCLEANED_RATIO = 0.20
REVISIT_FORCE_COOLDOWN_SEC = 1.6
TARGET_LATERAL_MIN_M = 0.22
TARGET_AHEAD_LATERAL_TOL_M = 0.34
TARGET_AHEAD_MIN_FORWARD_M = 0.22
UNDER_FURNITURE_REVISIT_CLEANED_RATIO = 0.58
UNDER_FURNITURE_REVISIT_MAX_UNCLEANED_RATIO = 0.22
UNDER_FURNITURE_REVISIT_COOLDOWN_SEC = 1.4
RECENT_VISIT_ROUTE_MEMORY_ENABLED = True
RECENT_VISIT_RADIUS_M = 0.22
RECENT_VISIT_UPDATE = 1.0
RECENT_VISIT_MAX = 8.0
RECENT_VISIT_DECAY_STEPS = 5
RECENT_VISIT_DECAY = 0.90
RECENT_VISIT_ROUTE_PENALTY = 1.85
RECENT_VISIT_TARGET_PENALTY = 10.5
RECENT_VISIT_TARGET_SOFT_BLOCK = 0.78
RECENT_VISIT_LOW_VALUE_EPS = 0.05
# Round 6n: weight of the recently-visited-area penalty for FRONTIER targets (kind_code 2).
# Was a hardcoded 0.25 in plan_best_coverage_route, i.e. recency for frontiers maxed at
# 0.25*10.5=2.6 against frontier scores of ~150-180 — effectively off, so the robot kept
# re-picking the same nearby thrashed frontier cluster (explored plateaued at 92%, 8 blacklists,
# no unknown-collapse).  Frontier near-vs-far differs by ~5.2/m * dcost ~= 8-13 pts; this scale is
# sized so a thrashed cell (recent_target~0.5-0.8) costs ~8-17 pts and loses to a fresh far
# frontier.  uncleaned targets keep the full (1.0) recency penalty at line ~10281.
EXPLORATION_FRONTIER_RECENT_VISIT_PENALTY_SCALE = 1.5
FRONT_NARROW_FRACTION = 0.16
ROW_END_CONFIRM_FRAMES = 11
ROW_END_CONFIRM_DISTANCE = 0.105
ROW_END_HARD_DISTANCE = 0.038
ROW_SLOW_DISTANCE = 0.135
FLOOR_FALSE_BLOCK_UPPER_OPEN = 0.70
FLOOR_FALSE_BLOCK_CENTER_OPEN = 0.70
FLOOR_FALSE_BLOCK_HOLD_SEC = 0.35
HEADING_LOCK_KP = 2.35
HEADING_LOCK_MAX_CORRECTION = 0.38
PIVOT_TURN_ANGLE = math.radians(90.0)
PIVOT_TURN_TOLERANCE = math.radians(0.9)
PIVOT_TURN_SPEED = 2.45
PIVOT_TURN_MIN_SPEED = 0.52
PIVOT_TURN_KP = 2.05
PIVOT_FINE_ZONE = math.radians(12.0)
PIVOT_FINE_MIN_SPEED = 0.62
PIVOT_FINE_MAX_SPEED = 0.88
PIVOT_FINAL_ZONE = math.radians(3.0)
PIVOT_FINAL_MIN_SPEED = 0.50
PIVOT_FINAL_MAX_SPEED = 0.66
PIVOT_ENCODER_KP = 0.85
PIVOT_WHEEL_TARGET_RAD = (WHEEL_BASE * PIVOT_TURN_ANGLE) / (2.0 * WHEEL_RADIUS)
PIVOT_WHEEL_TOLERANCE_RAD = 0.045
TURN_SETTLE_SEC = 0.70
PIVOT_FRONT_CLEARANCE = 0.20
PIVOT_BODY_CLEARANCE = 0.12
PRE_PIVOT_BACKUP_DISTANCE = 0.085
PRE_PIVOT_BACKUP_SPEED = 1.05
PRE_PIVOT_BACKUP_TIMEOUT_SEC = 0.80
PIVOT_WATCHDOG_TIMEOUT_SEC = 6.4
PIVOT_WATCHDOG_STALL_SEC = 2.20
PIVOT_WATCHDOG_PROGRESS_DEG = 2.0
PIVOT_WATCHDOG_MIN_ERR_DEG = 3.0
PIVOT_WATCHDOG_MAX_RETRIES = 1
UNKNOWN_COLOR = (155, 155, 155)
FREE_COLOR = (238, 238, 238)
OCC_COLOR = (15, 15, 15)
GRID_COLOR = (190, 190, 190)
TRAJ_COLOR = (40, 140, 255)
ROBOT_COLOR = (0, 0, 255)
FOV_COLOR = (70, 180, 70)
CLEANED_COLOR = (205, 245, 225)
CV_SEEN_COLOR = (235, 150, 235)
CV_DENSE_COLOR = (105, 25, 135)
CV_DISPLAY_LIGHT_EPS = 0.55
CV_DISPLAY_DENSE_EPS = 2.15
SHOW_MAP_LEGEND = True
SHOW_COVERAGE_PLANNER_WINDOW = True
PLANNER_ENABLED = True
PLANNER_UPDATE_STEPS = 70
PLANNER_TARGET_SEARCH_RADIUS_M = 2.6
PLANNER_GRID_STEP_PX = 9
PLANNER_UNKNOWN_FRONTIER_BONUS = 7.0
PLANNER_UNCLEANED_BONUS = 14.0
PLANNER_SIDE_BIAS = 7.0
PLANNER_TARGET_REACHED_M = 0.32
GLOBAL_ROUTE_PLANNER_ENABLED = True
GLOBAL_ROUTE_GRID_STEP_PX = 14
GLOBAL_ROUTE_OBSTACLE_INFLATE_PX = 5
GLOBAL_ROUTE_OBSTACLE_RATIO_BLOCK = 0.12
GLOBAL_ROUTE_MIN_CLEANABLE_RATIO = 0.12
GLOBAL_ROUTE_TARGET_UNCLEANED_RATIO = 0.09
GLOBAL_ROUTE_TARGET_FRONTIER_RATIO = 0.18
GLOBAL_ROUTE_TARGET_UNDER_RATIO = 0.08
GLOBAL_ROUTE_MAX_NODES = 9000
GLOBAL_ROUTE_COST_PENALTY = 3.05
GLOBAL_ROUTE_CLEANED_TRANSIT_PENALTY = 0.38
GLOBAL_ROUTE_RECENT_TRANSIT_PENALTY = 0.55
GLOBAL_ROUTE_TURN_PENALTY = 2.45
GLOBAL_ROUTE_LATERAL_PENALTY = 0.32
GLOBAL_ROUTE_FORWARD_BONUS = 1.35
GLOBAL_ROUTE_UNDER_MAX_DIST_M = 0.62
GLOBAL_ROUTE_WAYPOINT_LOOKAHEAD_M = 0.24
GLOBAL_ROUTE_CARDINAL_ONLY = True
GLOBAL_ROUTE_MIN_TARGET_DIST_M = 0.22
GLOBAL_ROUTE_STATUS_DECAY_SEC = 2.0
PLANNED_COVERAGE_ENABLED = True
MAP_MATURE_COVERAGE_PERCENT = 62.0
MAP_MATURE_MIN_TIME_SEC = 110.0
MAP_MATURE_TIME_COVERAGE_PERCENT = 48.0
MAP_MATURE_MAX_FRONTIER_RATIO = 0.055
# The timeout maturity path looks only at the BOUNDARY frontier ratio, so it can
# declare the map "mature" while a large INTERIOR gray gap is still open (the room
# is not actually closed).  Block the timeout path while the gray gap exceeds
# this; the high-coverage path is unaffected.  The progress governor still docks
# eventually if that gray is genuinely unreachable.
MAP_MATURE_MAX_GRAY_GAP_CELLS = 2500
MAP_MATURE_MIN_CLEANABLE_CELLS = 1800
ROUTE_COMMIT_MIN_COVERAGE_PERCENT = 55.0
ROUTE_COMMIT_MAX_ROUTE_COST_M = 2.35
ROUTE_COMMIT_MIN_ROUTE_LEN = 2
ROUTE_COMMIT_TARGET_REACHED_M = 0.27
ROUTE_COMMIT_WAYPOINT_REACHED_M = 0.14
ROUTE_COMMIT_WAYPOINT_LOOKAHEAD_M = 0.22
ROUTE_COMMIT_CORNER_SLOWDOWN_M = 0.28
ROUTE_COMMIT_ALIGN_TOL = math.radians(7.5)
ROUTE_COMMIT_PIVOT_KP = 2.9
ROUTE_COMMIT_PIVOT_MIN_SPEED = 0.62
ROUTE_COMMIT_PIVOT_MAX_SPEED = 1.95
ROUTE_COMMIT_SPEED = 2.25
ROUTE_COMMIT_SLOW_SPEED = 1.15
ROUTE_COMMIT_SEGMENT_FOLLOW_ENABLED = True
ROUTE_COMMIT_SEGMENT_ALIGN_TOL = math.radians(5.0)
ROUTE_COMMIT_SEGMENT_LATERAL_REACHED_M = 0.18
ROUTE_COMMIT_SEGMENT_ADVANCE_M = 0.11
ROUTE_COMMIT_WALL_STRIP_PRIORITY_ENABLED = True
ROUTE_COMMIT_WALL_STRIP_BONUS = 5.5
ROUTE_COMMIT_WALL_STRIP_CONTINUITY_BONUS = 2.8
RETURN_HOME_ENABLED = True
DOCK_TARGET_X = 0.0
DOCK_TARGET_Y = 0.0
DOCK_FINAL_HEADING = 0.0
DOCK_TARGET_REACHED_M = 0.24
DOCK_ALIGN_TOL = math.radians(8.0)
DOCK_RETURN_COVERAGE_PERCENT = 98.5
DOCK_RETURN_MIN_TIME_SEC = 90.0
DOCK_RETURN_MAX_ROUTE_COST_M = 18.0
DOCK_ROUTE_REPLAN_INTERVAL_SEC = 2.8
DOCK_ROUTE_START_COOLDOWN_SEC = 2.0
DOCK_ROUTE_MAX_AGE_SEC = 95.0
DOCK_ROUTE_GRID_PADDING_M = 0.85
DOCK_ROUTE_NEAREST_GOAL_RADIUS = 8
DOCK_STUCK_RETURN_COVERAGE_PERCENT = 96.0
DOCK_STUCK_RECOVERY_SEC = 7.0
# Mature dock-return wall-stall watchdog.  When the map is MATURE and the robot
# should be heading home but is looping recovery/realign maneuvers against a wall
# (chasing unreachable edge targets) without getting closer to the dock, blacklist
# the edge target, back away from the wall and re-commit the dock route.  Unlike
# DOCK_STUCK_* above this does NOT require near-complete coverage.
MATURE_DOCK_STALL_WATCHDOG_ENABLED = True
MATURE_DOCK_STALL_SEC = 28.0
MATURE_DOCK_STALL_PROGRESS_M = 0.30
MATURE_DOCK_STALL_ACTION_COOLDOWN_SEC = 10.0
MATURE_DOCK_STALL_BLACKLIST_RADIUS_M = 0.80
MATURE_DOCK_STALL_BLACKLIST_SEC = 150.0

# Wall-trapped frontier watchdog (exploration phase).  When the robot oscillates
# along a wall chasing a frontier that sits in a strip too narrow to enter (the
# side wall is not in the forward camera FOV, so the strip never closes), first
# do ONE look-around scan to honestly map the wall; if the frontier is still
# trapped after that, blacklist it so the planner moves on to reachable unknown.
WALL_TRAP_FRONTIER_WATCHDOG_ENABLED = True
WALL_TRAP_FRONTIER_NEAR_M = 0.42
WALL_TRAP_FRONTIER_ANCHOR_EPS_M = 0.32
WALL_TRAP_FRONTIER_STALL_SEC = 22.0
WALL_TRAP_FRONTIER_ACTION_COOLDOWN_SEC = 8.0
WALL_TRAP_FRONTIER_BLACKLIST_RADIUS_M = 0.55
WALL_TRAP_FRONTIER_BLACKLIST_SEC = 120.0
# Zone escape: the trap signature is the ROBOT pinned in one wall column (it can
# still drive up/down the strip and the frontier candidate can jump along the
# wall), making no coverage progress.  Anchor on the robot column + coverage, so
# a jumping candidate no longer resets the timer.  After a few failed actions in
# the same zone, blacklist the whole stuck strip with a large radius so the
# picker is forced to a far reachable region instead of hugging the wall.
WALL_TRAP_FRONTIER_ZONE_COV_GAIN_PERCENT = 0.4
WALL_TRAP_FRONTIER_ZONE_BLACKLIST_RADIUS_M = 1.2
WALL_TRAP_FRONTIER_ZONE_MAX_ACTIONS = 2
# Round 6o: once the room has closed, the wall-trap watchdog resets on real mapping
# progress (interior gray shrinking) instead of coverage growth.  Driving up/down an
# occluded wall strip cleans floor (coverage +0.4% -> old cov-gain reset) while mapping
# nothing (gray flat because the cells are behind an obstacle), which kept resetting the
# trap and let the robot oscillate.  Reset only if gray drops by at least this many cells.
WALL_TRAP_FRONTIER_ZONE_GRAY_DROP_CELLS = 300
DOCK_STOP_HOLD_OWNER_SEC = 9999.0
# Map-only mission: when False the robot still explores and returns to the dock,
# but it STOPS there instead of starting the learned-map K cleaning / coverage
# route phase.  Set False to focus purely on building the map.
AUTO_LEARNED_MAP_CLEANING_ENABLED = False
# Map-only mission: when the robot finishes exploring and parks on the dock,
# automatically write the occupancy + coverage maps (and metrics) to disk, so the
# mission ends with a saved map without needing the manual 'S' keypress.
AUTO_SAVE_MAP_ON_DOCK = True
AUTO_MAP_COMPLETE_MIN_TIME_SEC = 118.0
AUTO_MAP_COMPLETE_MIN_COVERAGE_PERCENT = 47.0
AUTO_MAP_COMPLETE_STRONG_COVERAGE_PERCENT = 54.0
AUTO_MAP_COMPLETE_MIN_CLEANABLE_CELLS = 7000
AUTO_MAP_COMPLETE_MAX_FRONTIER_RATIO = 0.052
AUTO_MAP_COMPLETE_MAX_FRONTIER_CELLS = 1150
AUTO_MAP_COMPLETE_MIN_OBSTACLE_CELLS = 850
AUTO_MAP_COMPLETE_PLATEAU_GAIN_PERCENT = 0.8
AUTO_MAP_COMPLETE_PLATEAU_SEC = 18.0
AUTO_MAP_COMPLETE_REQUIRE_FORWARD_STATE = False
AUTO_MAP_COMPLETE_MAX_GRAY_GAP_CELLS = 220
AUTO_MAP_COMPLETE_MAX_GRAY_GAP_COMPONENTS = 1
AUTO_MAP_COMPLETE_FRONTIER_OR_GRAY_RATIO = 0.085
AUTO_MAP_COMPLETE_NO_ROUTE_OK_SEC = 24.0
AUTO_MAP_COMPLETE_ARENA_GATE_ENABLED = True
AUTO_MAP_COMPLETE_MIN_ARENA_KNOWN_RATIO = 0.54
AUTO_MAP_COMPLETE_MIN_BOTTOM_BAND_KNOWN_RATIO = 0.30
AUTO_MAP_COMPLETE_BOTTOM_BAND_M = 0.85
# Frontier interior clip: drop frontiers that sit in the unknown background OUTSIDE
# the observed room envelope (beyond the walls). The base frontier is "unknown next
# to free floor", which also fires along the wall line pointing OUT of the room, so
# the robot chases unreachable ghost frontiers, camps the wall, loops forever and
# never finishes the map. The room envelope is taken from sensor evidence only (free
# floor + obstacles), NOT the known arena rectangle. Gated on coverage so early
# outward exploration is not blocked. CLOSE_M bridges small unmapped wall gaps so the
# flood does not leak out (a real doorway wider than ~2*CLOSE_M is still explored).
FRONTIER_INTERIOR_CLIP_ENABLED = True
# Primary gate = loop closure, NOT coverage %. Coverage is cleaned / KNOWN-floor, and the
# known floor grows as we explore, so the % is relative to a moving denominator and cannot
# tell us how much map is left. Instead: once the observed free-floor+obstacle ring encloses
# at least this much interior area (the gray middle the border-flood cannot reach), the room
# has "closed" -> latch it and keep the clip on. Below closure, frontiers stay unrestricted
# so the robot keeps expanding outward to actually close the room.
FRONTIER_ROOM_CLOSED_MIN_AREA_M2 = 3.0
FRONTIER_INTERIOR_CLIP_MIN_COVERAGE = 25.0   # low safety floor only; closure is the real gate
FRONTIER_INTERIOR_CLIP_CLOSE_M = 0.30
GRAY_REVISIT_ENABLED = True
GRAY_REVISIT_MIN_COMPONENT_CELLS = 55
GRAY_REVISIT_MAX_COMPONENT_CELLS = 15000
GRAY_REVISIT_NEAR_CLEANABLE_M = 0.74
GRAY_REVISIT_FRONTIER_DILATE_M = 0.10
GRAY_REVISIT_BBOX_PAD_M = 0.42
GRAY_REVISIT_REJECT_BBOX_EDGE_PAD_PX = 3
GRAY_REVISIT_MAX_COMPONENTS_FOR_DEBUG = 16
GRAY_REVISIT_OBSTACLE_EDGE_DILATE_M = 0.13
GRAY_REVISIT_MIN_CLEANABLE_EDGE_CELLS = 28
GRAY_REVISIT_MIN_CLEANABLE_EDGE_RATIO = 0.16
GRAY_REVISIT_MAX_OBSTACLE_EDGE_RATIO = 0.50
GRAY_REVISIT_OBSTACLE_SHADOW_RATIO = 1.35
# A gray component is treated as a furniture *shadow* (unseen object interior to be
# walled off) only when its boundary is obstacle-dominated AND it is bounded in size.
# Larger gray patches are unexplored floor pockets: keep them explorable as frontiers
# instead of fencing them off. Set <=0 to fall back to the legacy low-clean heuristic.
GRAY_REVISIT_SHADOW_MAX_AREA_RATIO = 0.60
GRAY_REVISIT_SHADOW_REQUIRE_OBSTACLE_EDGE = True
OBSTACLE_HYPOTHESIS_ENABLED = True
OBSTACLE_HYPOTHESIS_UPDATE_STEPS = 14
OBSTACLE_HYPOTHESIS_OCC_EPS = 0.85
OBSTACLE_HYPOTHESIS_MAX = 4.0
OBSTACLE_HYPOTHESIS_DECAY = -0.055
OBSTACLE_HYPOTHESIS_FREE_CLEAR_LO = -2.25
# Shape completion excludes "already observed free" interior from being painted as
# obstacle, so the fill never covers real floor.  But the exclusion threshold must
# be MODERATE, not the barely-free unknown epsilon: a single grazing depth ray near
# an obstacle pushes interior cells just below -LO_UNKNOWN_EPS (-0.18), which used to
# permanently disqualify the whole silhouette from filling.  Once the robot stopped
# camping and started driving all the way around obstacles (Round 6), every interior
# got grazed -> obstacles went hollow ("перестал закрашивать препятствия").  Require
# the cell to be CONFIDENTLY free (repeated/strong observation) before excluding it;
# weak/noisy grazing free still fills as obstacle interior.  cleaned floor + strong
# free are still excluded, so this does not re-open the old over-fill.
# REVERTED to the good-path value.  Rounds 6c–6f widened this (and the gates below)
# to fix the DISPLAY, but the hypothesis layer is ALSO read by the planner
# (frontier_unknown = unknown & ~hyp_shadow, and closure's known |= hypObs), so
# inflating it perturbed frontier selection / path.  Display is now handled by the
# separate deterministic body fill (build_obstacle_body_fill), so the inference
# layer is restored to its small, planning-safe form.
OBSTACLE_HYPOTHESIS_OBSERVED_FREE_LO = -0.18
OBSTACLE_HYPOTHESIS_MIN_COMPONENT_CELLS = 18
# Never-filled obstacles.  Two gates were silently rejecting whole obstacles the user
# can clearly see outlined in black points:
#  - a big piece of furniture (e.g. the bottom-left rectangle) exceeds the old span /
#    area caps and is dropped as "too big, probably a wall" -> raise the caps.  Walls
#    are still excluded separately by the arena-wall-touch + map-edge test, so this
#    does not start filling the room perimeter.
#  - the morphological CLOSE kernel was BOX_PAD_M=0.055m (~3px), too small to bridge
#    the gaps between SPARSE studded points, so a 4-sided ring of dots never became a
#    single connected island with an enclosed interior -> it never qualified.  A wider
#    close (~7px) bridges the studs so the silhouette connects and its interior fills.
OBSTACLE_HYPOTHESIS_MAX_COMPONENT_CELLS = 3600
OBSTACLE_HYPOTHESIS_MAX_SPAN_M = 1.85
OBSTACLE_HYPOTHESIS_BOX_PAD_M = 0.055
OBSTACLE_HYPOTHESIS_MIN_SIDE_SUPPORT = 4
OBSTACLE_HYPOTHESIS_MIN_SIDE_COUNT = 3
# Qualify gate, NOT a fill mask: an obstacle island is rejected outright if more
# than this fraction of its bbox reads observed-free.  At 0.10 a low/thin obstacle
# standing on open floor (grazed by depth rays from the sides) keeps flunking the
# gate, so its fill drops out and re-appears tick to tick (the flicker the user
# sees).  Raise it so a grazed obstacle still qualifies.  Safe because the fill is
# still only `roi_unknownish` (unknown cells) — qualifying never paints real floor.
OBSTACLE_HYPOTHESIS_MAX_FREE_RATIO = 0.10
OBSTACLE_HYPOTHESIS_MIN_FILL_CELLS = 8
OBSTACLE_HYPOTHESIS_SHADOW_UPDATE = 0.72
# One-shot stickiness (flicker root cause).  At 1.10 a cell that only qualifies for
# shape-completion INTERMITTENTLY (a big obstacle whose free_ratio crosses the gate
# tick-to-tick) never climbs above the sticky-keep floor (2.5): it gets +1.10, decays
# before the next qualify, gets +1.10 again... so it lives in the maskable [0.85,2.5]
# band and blinks on/off with every grazing free ray.  Jumping straight to MAX on a
# single qualification makes the cell sticky immediately, so it stops flickering; the
# free-clear still erodes it from MAX over ~9 sustained-free recomputes if it is truly
# floor.  (A stable island already reached MAX after ~4 adds — that is why the first
# obstacle never flickered while later ones did.)
OBSTACLE_HYPOTHESIS_SHAPE_UPDATE = 1.10
# Stickiness: a cell whose accumulated hypothesis log-odds is at least this strong
# is NOT hidden just because the base occupancy momentarily reads strong-free.  This
# is what stops the fill from blinking off for a tick every time a depth ray grazes
# a low/thin obstacle (the base flips < FREE_CLEAR_LO for one frame).  A cell only
# reaches this by being re-shape-completed several times (SHAPE_UPDATE=1.10 each), so
# noise stamps never stick; and the gentle free-clear still drives genuinely-free
# cells back below it over a few seconds, so sustained free still wins (honesty).
OBSTACLE_HYPOTHESIS_STICKY_KEEP_LO = 2.5
OBSTACLE_HYPOTHESIS_UNKNOWN_DECAY_MULT = 2.0
# MAPPING mission: do NOT let inferred/hallucinated obstacle interiors (the orange
# hypothesis layer) block the planner.  The mission is to map *observed* reality, and
# the shape-completion path was stamping a persistent ~626-cell phantom obstacle from
# t=18s that inflated noGo and fenced the planner.  hypObs is kept as a visual overlay
# (still drawn) but is no longer a hard no-go.  Set True to restore the old behavior.
OBSTACLE_HYPOTHESIS_NO_GO_IN_PLANNING = False
OBSTACLE_HYPOTHESIS_DRAW_LABELS = True

# --- Deterministic obstacle BODY fill (display only) ----------------------------
# The speculative hypothesis log-odds layer above accumulates/decays per recompute,
# which made the orange obstacle fill flicker and miss large/sparse obstacles no
# matter how the thresholds were tuned.  Because hypObs is visual-only in this
# mapping mission (NO_GO_IN_PLANNING=False), the obstacle *body* shown on the maps is
# instead rebuilt geometrically every frame from CONFIRMED obstacle cells: bridge
# sparse studded points (morphological close), then solid-fill the interior enclosed
# by each bounded cluster.  Recomputed from confirmed evidence each render => no
# decay, no flicker, and large/sparse silhouettes fill reliably.  Walls / room
# perimeter are excluded per-component (span cap + arena-wall touch + map edge), and
# confidently-free / cleaned cells are never painted, so it cannot bleed onto floor
# or flood the room.  Set False to fall back to the raw hypothesis overlay.
OBSTACLE_BODY_FILL_ENABLED = True
OBSTACLE_BODY_FILL_CLOSE_M = 0.28          # Round 6t: 0.14->0.28. Obstacles arrive as sparse studded points (rawObs ~200, not dense silhouettes); a 0.14m (~7px) close left studs >14cm apart unconnected so almost nothing reached the 18-cell fill floor (bodyFill~64). 0.28m bridges studs into fillable bodies. Wall-touch + span cap + ~free/~cleaned still prevent painting walls/floor.
OBSTACLE_BODY_FILL_MAX_SPAN_M = 4.5        # Round 6q: 2.6->4.5; real furniture (tables) exceed 2.6m and were dropped as "wall". Wall ring (~14-18m) still excluded by this cap + wall-touch + map-edge
OBSTACLE_BODY_FILL_MIN_COMPONENT_CELLS = 18
# Round 6l: fill PARTIAL silhouettes, not only fully-closed rings.  Use confidently-free
# floor the robot drove around the obstacle as an extra flood barrier so the unknown
# interior trapped between the seen faces and that floor is filled.  A lone unobserved
# face stays connected to the open room and is never claimed.  False = legacy enclosed-
# ring-only fill (the old behaviour that left every not-fully-circled object unpainted).
OBSTACLE_BODY_FILL_FLOOR_BARRIER = True
OBSTACLE_BODY_FILL_BARRIER_PAD_M = 0.30    # surrounding observed-free floor included to close a silhouette's open sides
# Round 6t: complete each studded obstacle cluster to a standard PRIMITIVE (the tighter of
# min-area-rectangle / min-enclosing-circle) and fill it solid.  Furniture is rectangular or
# round, but RGB-D gives only a sparse studded outline with gray floor inside; fitting a
# primitive reconstructs the implied body cleanly.  Falls back to flood fill when the fit
# would land mostly on observed-free floor (a bad fit across open space).  Display only.
OBSTACLE_BODY_FILL_FIT_PRIMITIVES = True
OBSTACLE_BODY_FILL_FIT_MAX_FREE_RATIO = 0.55  # reject a fitted primitive if more than this fraction of it is confidently-free floor
# Round 6u: gray-bridged geometric completion. A sparse studded outline fragments into arcs
# and a big object's gray (unknown) interior stays unfilled. Let the interior gray itself
# bridge the gaps: seed = obstacle points + unknown cells within a short radius of them, so
# the whole object becomes ONE cluster; then fit + fill a rectangle/circle to the real points.
# Implements "gray walled by points that looks like a figure = obstacle body". Display only.
OBSTACLE_BODY_FILL_GRAY_BRIDGE = True
OBSTACLE_BODY_FILL_GRAY_BRIDGE_M = 0.40       # close radius to bridge outline gaps in the obstacle POINTS (bounded). Round 6u-fix: was 0.55 + gray-dilation, which stitched noise through open gray into a giant phantom; now points-only close, gray used only as enclosed interior
OBSTACLE_BODY_FILL_GRAY_MIN_EVIDENCE = 0.60   # keep a fitted figure only if its ENCLOSED body fills >= this fraction of the rect/circle (rejects phantom rects over scattered points in open space)
# Round 6v: use the BLUE driveable floor (free + cleaned) as the obstacle boundary. The robot
# drives free floor all around furniture, so each obstacle is a non-blue region ENCLOSED by blue
# floor. Far more robust than fitting sparse outline points. Takes precedence over gray-bridge.
# Guard against painting an unexplored pocket the path merely looped around: keep an enclosed
# region only when its perimeter is lined with obstacle points (the robot actually sensed an
# obstacle at the floor boundary), not just because it is surrounded by floor.
OBSTACLE_BODY_FILL_FLOOR_ENCLOSED = True
OBSTACLE_BODY_FILL_FLOOR_COVER_M = 0.30       # dilation radius to cluster perimeter studs into one obstacle (bridges sparse studs)
OBSTACLE_BODY_FILL_FLOOR_MIN_PTS = 40         # min obstacle-points in the main cluster to accept a fill (drops small junk fills from a few scattered points)
NEAR_COLLISION_HYPOTHESIS_ENABLED = True
NEAR_COLLISION_HYPOTHESIS_MIN_COV_PERCENT = 24.0
NEAR_COLLISION_HYPOTHESIS_FRONT_M = 0.34
NEAR_COLLISION_HYPOTHESIS_BODY_M = 0.055
NEAR_COLLISION_HYPOTHESIS_RADIUS_M = 0.045
NEAR_COLLISION_HYPOTHESIS_COOLDOWN_SEC = 1.5
LEARNED_MAP_SANITIZE_FREE_LO = -2.85
LEARNED_MAP_SANITIZE_OCC_LO = 4.85
LEARNED_MAP_SANITIZE_STRUCTURAL_OCC = 3.65
LEARNED_MAP_SANITIZE_VISUAL_OCC = 1.05
LEARNED_MAP_SANITIZE_REMOVE_WEAK_OUTSIDE = True
LEARNED_MAP_DOCK_CLEAR_RADIUS_M = 0.34
LEARNED_MAP_SANITIZE_STRONG_NOISE_CLEANUP = True
LEARNED_MAP_SANITIZE_MIN_OBS_AREA_PX = 10
LEARNED_MAP_SANITIZE_MIN_OBS_SPAN_PX = 5
LEARNED_MAP_SANITIZE_RAY_MAX_AREA_PX = 190
LEARNED_MAP_SANITIZE_RAY_MIN_SPAN_PX = 14
LEARNED_MAP_SANITIZE_RAY_MAX_DENSITY = 0.23
LEARNED_MAP_SANITIZE_DENSE_CLOSE_M = 0.055
LEARNED_MAP_K_START_HOLD_SEC = 0.20
ROUTE_COMMIT_FRONT_ABORT_M = max(ROW_END_HARD_DISTANCE, 0.135)
ROUTE_COMMIT_CENTER_ABORT_M = SAFE_FRONT_DISTANCE * 0.86
ROUTE_COMMIT_BODY_ABORT_M = BODY_CORRIDOR_HARD_CLEARANCE
ROUTE_COMMIT_MAX_AGE_SEC = 22.0
ROUTE_COMMIT_REPLAN_COOLDOWN_SEC = 1.6
ROUTE_COMMIT_LOCAL_UNCLEANED_MIN_CELLS = 20
ROUTE_COMMIT_BLOCKED_RATIO_ABORT = 0.24
ROUTE_COMMIT_SCORE_MARGIN = 1.5
HYBRID_COVERAGE_ENABLED = True
PLANNER_CONFIDENCE_PARTIAL_COVERAGE_PERCENT = 28.0
PLANNER_CONFIDENCE_PARTIAL_MIN_TIME_SEC = 45.0
PLANNER_CONFIDENCE_PARTIAL_MAX_FRONTIER_RATIO = 0.22
SHORT_ROUTE_COMMIT_ENABLED = True
SHORT_ROUTE_COMMIT_MIN_COVERAGE_PERCENT = 24.0
SHORT_ROUTE_COMMIT_MAX_ROUTE_COST_M = 1.35
SHORT_ROUTE_COMMIT_MAX_STRAIGHT_DIST_M = 1.55
SHORT_ROUTE_COMMIT_MAX_TURN_FRAC = 0.62
SHORT_ROUTE_COMMIT_MIN_SCORE = 4.8
SHORT_ROUTE_COMMIT_MIN_COMPONENT_CELLS = 2
PARTIAL_ROUTE_COMMIT_MIN_COVERAGE_PERCENT = 28.0
PARTIAL_ROUTE_COMMIT_MAX_ROUTE_COST_M = 1.90
PARTIAL_ROUTE_COMMIT_MAX_STRAIGHT_DIST_M = 2.10
PARTIAL_ROUTE_COMMIT_MAX_TURN_FRAC = 0.72
PARTIAL_ROUTE_COMMIT_MIN_SCORE = 3.5
PARTIAL_ROUTE_COMMIT_MIN_COMPONENT_CELLS = 3
ROUTE_COMMIT_PREEMPT_ROW_FORWARD = True
GLOBAL_ROUTE_CONTINUITY_BONUS = 2.8
GLOBAL_ROUTE_WALL_CONTINUITY_BONUS = 1.2
GLOBAL_ROUTE_TOP_DEBUG_COUNT = 3
COVERAGE_TARGET_STICKY_ENABLED = True
COVERAGE_TARGET_STICKY_SEC = 5.5
COVERAGE_TARGET_STICKY_RADIUS_M = 0.52
COVERAGE_TARGET_STICKY_SCORE_MARGIN = 5.0
COVERAGE_TARGET_STICKY_MIN_COMP_CELLS = 3
DOCK_LOITER_GUARD_ENABLED = True
DOCK_LOITER_GUARD_COVERAGE_PERCENT = 58.0
DOCK_LOITER_GUARD_RADIUS_M = 1.18
DOCK_LOITER_GUARD_MIN_COMP_CELLS = 260
DOCK_LOITER_GUARD_FRONTIER_ALWAYS = True
MISSED_STRIP_RECOVERY_ENABLED = True
MISSED_STRIP_MIN_COVERAGE_PERCENT = 32.0
MISSED_STRIP_MIN_COMPONENT_CELLS_PARTIAL = 10
MISSED_STRIP_MIN_COMPONENT_CELLS_MATURE = 5
MISSED_STRIP_MIN_SPAN_CELLS = 4
MISSED_STRIP_MIN_WALL_CONTACTS = 2
MISSED_STRIP_PROMOTE_REWARD = 5.5
MISSED_STRIP_SCORE_BONUS = 7.5
MISSED_STRIP_WALL_CONTACT_SCALE = 0.08
MISSED_STRIP_MAX_BONUS = 11.0
LARGE_UNCLEANED_COMPONENT_BONUS_SCALE = 0.035
LARGE_UNCLEANED_COMPONENT_BONUS_MAX = 5.0
STALE_UNCLEANED_COMPONENT_BONUS = 2.0
COVERAGE_TARGET_STICKY_BREAK_MARGIN = 1.2
COVERAGE_TARGET_STICKY_BREAK_MISSED_STRIP_BONUS = 3.5
REJECTED_COMPONENT_DEBUG_COUNT = 4
COVERAGE_FOOTPRINT_TARGETING_ENABLED = True
GLOBAL_ROUTE_REQUIRE_CENTER_FOOTPRINT = True
COVERAGE_FOOTPRINT_MIN_GAIN_CELLS = 12
COVERAGE_FOOTPRINT_MIN_GAIN_RATIO = 0.035
COVERAGE_FOOTPRINT_TARGET_GAIN_SCALE = 0.045
COVERAGE_FOOTPRINT_TARGET_GAIN_MAX = 7.0
COVERAGE_FOOTPRINT_TARGET_RECLEAN_PENALTY = 4.2
COVERAGE_FOOTPRINT_ROUTE_RECLEAN_PENALTY = 0.85
COVERAGE_FOOTPRINT_ROUTE_GAIN_DISCOUNT = 0.32
COVERAGE_FOOTPRINT_ROUTE_MIN_COST_FACTOR = 0.42
COVERAGE_FOOTPRINT_DEBUG_TOP_GAIN_CELLS = 0
COVERAGE_SEGMENT_PLANNER_ENABLED = True
COVERAGE_SEGMENT_MIN_COMP_CELLS = 7
COVERAGE_SEGMENT_MIN_SPAN_CELLS = 4
COVERAGE_SEGMENT_MIN_GAIN_CELLS = 18
COVERAGE_SEGMENT_MAX_CELLS = 32
COVERAGE_SEGMENT_GAIN_SCALE = 0.018
COVERAGE_SEGMENT_GAIN_MAX = 10.0
COVERAGE_SEGMENT_LENGTH_BONUS = 0.22
COVERAGE_SEGMENT_CONTINUITY_BONUS = 2.2
COVERAGE_SEGMENT_RECLEAN_PENALTY = 2.6
COVERAGE_SEGMENT_INTERNAL_COST_FACTOR = 0.32
COVERAGE_SEGMENT_STRIP_DEBUG_COUNT = 2
OBJECTIVE_NOISE_FILTER_ENABLED = True
OBJECTIVE_OBSTACLE_SPECKLE_MIN_AREA_PX = 14
OBJECTIVE_OBSTACLE_SPECKLE_MIN_SPAN_PX = 5
OBJECTIVE_OBSTACLE_KEEP_STRONG_COUNT = 3
OBJECTIVE_RAY_STREAK_FILTER_ENABLED = True
OBJECTIVE_RAY_STREAK_MIN_SPAN_PX = 16
OBJECTIVE_RAY_STREAK_MAX_AREA_PX = 460
OBJECTIVE_RAY_STREAK_MAX_DENSITY = 0.21
OBJECTIVE_RAY_STREAK_MAX_NARROW_PX = 7
OBJECTIVE_UNCLEANED_SPECKLE_MIN_AREA_PX = 12
OBJECTIVE_UNCLEANED_SPECKLE_MIN_SPAN_PX = 5
OBJECTIVE_UNCLEANED_KEEP_WALL_ADJACENT = True
OBJECTIVE_NOISE_NEAR_FLOOR_DILATE_PX = 2
ROUTE_COMMIT_TARGET_BLACKLIST_ENABLED = True
ROUTE_COMMIT_TARGET_BLACKLIST_RADIUS_M = 0.42
ROUTE_COMMIT_TARGET_BLACKLIST_SEC = 32.0
ROUTE_COMMIT_TARGET_BLACKLIST_MAX_ENTRIES = 24
ROUTE_COMMIT_BLACKLIST_ON_REASONS = (
    "blocked", "path blocked", "bumper", "timeout", "nav changed", "no progress",
    "contact", "body", "front", "rear", "map-edge",
)
ROUTE_COMMIT_NO_PROGRESS_TIMEOUT_SEC = 5.8
ROUTE_COMMIT_NO_PROGRESS_MIN_GAIN_M = 0.07
ROUTE_COMMIT_EDGE_RESIDUAL_GUARD_ENABLED = True
ROUTE_COMMIT_EDGE_RESIDUAL_COVERAGE_PERCENT = 72.0
ROUTE_COMMIT_EDGE_RESIDUAL_BAND_M = 0.34
ROUTE_COMMIT_EDGE_RESIDUAL_MIN_COMP_CELLS = 90
ROUTE_COMMIT_DOCK_RESIDUAL_GUARD_RADIUS_M = 0.90
ROUTE_COMMIT_DOCK_RESIDUAL_MIN_COMP_CELLS = 140
RESIDUAL_CLEANUP_COVERAGE_PERCENT = 88.0
RESIDUAL_ROUTE_SIDE_BIAS_PERCENT = 62.0
RESIDUAL_REPLAN_COVERAGE_PERCENT = 62.0
RESIDUAL_TARGET_LOCAL_RADIUS_M = 0.42
RESIDUAL_TARGET_MIN_LOCAL_CELLS_EARLY = 420
RESIDUAL_TARGET_MIN_LOCAL_CELLS_LATE = 90
RESIDUAL_TARGET_MAX_MID_PHASE_ROUTE_M = 1.15
RESIDUAL_TARGET_AHEAD_FORWARD_M = 0.32
RESIDUAL_TARGET_AHEAD_LATERAL_TOL_M = 0.22
RESIDUAL_TARGET_NEAR_DIRECT_M = 0.48
RESIDUAL_TARGET_ADJACENT_LINE_MAX_DIST_M = 0.90
RESIDUAL_TARGET_ADJACENT_LINE_MIN_FORWARD_M = -0.08
RESIDUAL_TARGET_ADJACENT_LINE_LATERAL_TOL_M = 0.52
RESIDUAL_TARGET_ADJACENT_LINE_MIN_CELLS = 160
EDGE_LINE_ACQUIRE_ENABLED = True
EDGE_LINE_ACQUIRE_MIN_COVERAGE_PERCENT = 25.0
EDGE_LINE_ACQUIRE_MAX_COVERAGE_PERCENT = 82.0
EDGE_LINE_ACQUIRE_MAX_DIST_M = 0.95
EDGE_LINE_ACQUIRE_MIN_FORWARD_M = -0.08
EDGE_LINE_ACQUIRE_MAX_FORWARD_M = 1.25
EDGE_LINE_ACQUIRE_MIN_LATERAL_M = 0.14
EDGE_LINE_ACQUIRE_MAX_LATERAL_M = 0.34
EDGE_LINE_ACQUIRE_MIN_SIDE_CLEAR_M = 0.24
EDGE_LINE_ACQUIRE_MIN_FRONT_M = 0.18
EDGE_LINE_ACQUIRE_MAX_ROUTE_COST_M = 1.25
EDGE_LINE_ACQUIRE_SPEED = 1.10
EDGE_LINE_ACQUIRE_SLOW_SPEED = 0.72
EDGE_LINE_ACQUIRE_YAW_KP = 1.05
EDGE_LINE_ACQUIRE_MAX_YAW = 0.18
EDGE_LINE_ACQUIRE_LOCK_SEC = 1.20
NEARBY_ROUTE_CLEANUP_ENABLED = True
NEARBY_ROUTE_CLEANUP_MIN_COVERAGE_PERCENT = 42.0
NEARBY_ROUTE_CLEANUP_MAX_COVERAGE_PERCENT = 88.0
NEARBY_ROUTE_CLEANUP_MAX_ROUTE_COST_M = 1.20
NEARBY_ROUTE_CLEANUP_MAX_DIST_M = 0.92
NEARBY_ROUTE_CLEANUP_MIN_LATERAL_M = 0.24
NEARBY_ROUTE_CLEANUP_MAX_LATERAL_M = 0.72
NEARBY_ROUTE_CLEANUP_MIN_FORWARD_M = -0.16
NEARBY_ROUTE_CLEANUP_MAX_FORWARD_M = 0.82
NEARBY_ROUTE_CLEANUP_MIN_ROW_PROGRESS_M = 0.48
NEARBY_ROUTE_CLEANUP_COOLDOWN_SEC = 3.8
NEARBY_ROUTE_CLEANUP_MIN_LOCAL_CELLS = 95
NEARBY_ROUTE_CLEANUP_SIDE_CLEAR_M = SIDE_DISTANCE + 0.08
NEARBY_ROUTE_CLEANUP_ALLOW_USEFUL_ROW_AFTER_M = 0.82
NEARBY_ROUTE_CLEANUP_USEFUL_ROW_UNCLEANED = 0.58
NEARBY_ROUTE_CLEANUP_USEFUL_ROW_CLEANED_MAX = 0.46
SIDE_STRIP_CLEANUP_ENABLED = True
SIDE_STRIP_CLEANUP_MIN_COVERAGE_PERCENT = 38.0
SIDE_STRIP_CLEANUP_MAX_COVERAGE_PERCENT = 88.0
SIDE_STRIP_CLEANUP_MIN_ROW_PROGRESS_M = 0.52
SIDE_STRIP_CLEANUP_COOLDOWN_SEC = 4.6
SIDE_STRIP_CLEANUP_SCAN_FORWARD_M = 0.95
SIDE_STRIP_CLEANUP_SCAN_BACK_M = 0.14
SIDE_STRIP_CLEANUP_LANE_OFFSET_M = LANE_SPACING
SIDE_STRIP_CLEANUP_HALF_WIDTH_M = 0.18
SIDE_STRIP_CLEANUP_STEP_M = 0.06
SIDE_STRIP_CLEANUP_MIN_UNCLEANED_CELLS = 28
SIDE_STRIP_CLEANUP_MAX_OBSTACLE_RATIO = 0.14
SIDE_STRIP_CLEANUP_MIN_SCORE = 20.0
SIDE_STRIP_CLEANUP_SCORE_MARGIN = 6.0
SIDE_STRIP_CLEANUP_SIDE_CLEAR_M = SIDE_DISTANCE + 0.07
SIDE_STRIP_CLEANUP_CURRENT_ROW_USEFUL_UNCLEANED = 0.46
SIDE_STRIP_CLEANUP_CURRENT_ROW_CLEANED_MAX = 0.54
SIDE_STRIP_CLEANUP_ROUTE_BONUS = 12.0
SIDE_STRIP_CLEANUP_WALL_FRINGE_BONUS = 7.0
EARLY_EXPLORATION_COVERAGE_PERCENT = 28.0
ROW_COMMIT_MIN_TIME_SEC = 4.8
ROW_COMMIT_MIN_DISTANCE_M = 0.95
ROW_COMMIT_FRONT_CLEARANCE_M = ROW_END_CONFIRM_DISTANCE + 0.05
ROUTE_GUIDANCE_BEHIND_DISABLE_M = -0.03
ROUTE_GUIDANCE_MAX_SIDE_ANGLE_DEG = 58.0
EARLY_EXPLORATION_DISABLE_TARGET_REPLAN = True
EARLY_EXPLORATION_LOCAL_DETOURS_PERCENT = EARLY_EXPLORATION_COVERAGE_PERCENT
LANE_ACTION_COOLDOWN_SEC = 2.8
LANE_ACTION_MIN_ROW_PROGRESS_M = 0.34
POST_LANE_FORWARD_LOCK_SEC = 2.6
POST_LANE_FORWARD_LOCK_DISTANCE_M = 0.46
POST_LANE_FORWARD_LOCK_SPEED = SLOW_SPEED
GRID_REALIGN_TOLERANCE = math.radians(2.2)
GRID_REALIGN_REQUEST_ERR = GRID_REALIGN_TOLERANCE + math.radians(0.25)
GRID_REALIGN_TIMEOUT_SEC = 2.2
GRID_REALIGN_MIN_SPEED = 0.34
GRID_REALIGN_MAX_SPEED = 2.05
GRID_REALIGN_KP = 2.2
GRID_REALIGN_RETRY_SEC = 0.65
GRID_REALIGN_TIMEOUT_ACCEPT_ERR = math.radians(5.0)
GRID_REALIGN_STALL_SEC = 0.55
GRID_REALIGN_PROGRESS_EPS = math.radians(0.7)
GRID_REALIGN_SOFT_ACCEPT_ERR = math.radians(4.0)
GRID_REALIGN_MAX_RETRIES = 1
FORWARD_STRAIGHT_REALIGN_ERR = math.radians(2.0)
FORWARD_STRAIGHT_REALIGN_MIN_FRONT_M = 0.18
FORWARD_STRAIGHT_RECOVERY_GRACE_SEC = 0.55
POST_RECOVERY_STABILIZER_ENABLED = True
POST_RECOVERY_STABILIZE_SEC = 1.0
POST_RECOVERY_STABILIZE_DISTANCE_M = 0.08
POST_RECOVERY_WALL_STABILIZE_SEC = 1.0
POST_RECOVERY_WALL_DISTANCE_M = 0.10
POST_RECOVERY_SPEED = 1.18
POST_RECOVERY_WALL_SPEED = 1.10
POST_RECOVERY_HEADING_TOL = math.radians(3.2)
POST_RECOVERY_REALIGN_ERR = math.radians(5.0)
POST_RECOVERY_HEADING_KP = 0.72
POST_RECOVERY_MAX_CORRECTION = 0.055
POST_RECOVERY_WALL_MAX_YAW = 0.035
POST_RECOVERY_HARD_FRONT_M = 0.105
POST_RECOVERY_HARD_CENTER_M = 0.125
POST_RECOVERY_BODY_HARD_MARGIN_M = 0.004
STRICT_MOTION_PRIMITIVES_ENABLED = True
STRICT_GRID_HEADING_LOCK_ENABLED = True
STRICT_WORLD_GRID_HEADING_ENABLED = True
STRICT_WORLD_GRID_SNAP_TOL = math.radians(2.5)
STRICT_GRID_HEADING_PIVOT_TOL = math.radians(0.85)
STRICT_GRID_HEADING_TINY_TOL = math.radians(0.18)
STRICT_GRID_TINY_CORRECTION = 0.135
STRICT_GRID_PIVOT_KP = 2.15
STRICT_GRID_PIVOT_MIN_SPEED = 0.62
STRICT_GRID_PIVOT_MAX_SPEED = 1.70
STRICT_CURVE_DIFF_THRESHOLD = 0.10
STRICT_ARC_ALLOWED_STATUS_KEYWORDS = (
    # Keep exceptions narrow.  Wall/post-recovery/line-acquire must not bypass
    # the grid lock, otherwise the robot leaves a contact at an arbitrary angle
    # and drives a visually diagonal row.
    "narrow", "gap mouth", "gap commit", "under furniture",
)
HARD_CONTROL_ARBITER_ENABLED = True
EXPLORE_SIMPLE_MODE_ENABLED = True
EXPLORE_SIMPLE_UNTIL_COVERAGE_PERCENT = 28.0
EXPLORE_SIMPLE_MIN_TIME_SEC = 55.0
ROW_OWNER_MIN_TIME_SEC = 1.10
ROW_OWNER_MIN_DISTANCE_M = 0.18
POST_MANEUVER_ROW_OWNER_TIME_SEC = 2.20
POST_MANEUVER_ROW_OWNER_DISTANCE_M = 0.28
GRID_REALIGN_OWNER_TIME_SEC = 2.20
PIVOT_OWNER_TIME_SEC = 3.20
LANE_SHIFT_OWNER_TIME_SEC = 4.20
OPTIONAL_PLANNER_SUPPRESS_AFTER_CONTACT_SEC = 2.20
HARD_CORE_CONTROLLER_ENABLED = True
HARD_CORE_DISABLE_LOCAL_ALIGNMENT = True
HARD_CORE_MAP_FIRST_ROW_M = 0.82
HARD_CORE_COVERAGE_ROW_M = 1.05
HARD_CORE_FINISH_ROW_M = 0.72
HARD_CORE_MIN_ROW_M = 0.36
HARD_CORE_FRONT_BLOCK_M = 0.16
HARD_CORE_CENTER_BLOCK_M = 0.16
HARD_CORE_UPPER_BLOCK_M = 0.22
HARD_CORE_BODY_BLOCK_M = BODY_CORRIDOR_HARD_CLEARANCE + 0.018
COVERAGE_BODY_ROW_END_SOFT_M = BODY_CORRIDOR_HARD_CLEARANCE + 0.030
HARD_CORE_ROW_END_CONFIRM_FRAMES = 3
HARD_CORE_REALIGN_ERR = math.radians(1.25)
HARD_CORE_REALIGN_MIN_FRONT_M = 0.25
HARD_CORE_TURN_COOLDOWN_SEC = 1.35
HARD_CORE_SPEED = CRUISE_SPEED
HARD_CORE_SLOW_SPEED = SLOW_SPEED
HARD_CORE_SIDE_CLOSE_M = SIDE_DISTANCE + 0.06
HARD_CORE_SIDE_OPEN_BONUS_M = 0.12
MATRIX_FIRST_PHASE_SPLIT_ENABLED = True
EXPLORE_DISABLE_FIXED_LAWNMOWER_ROWS = True
EXPLORE_DISABLE_LANE_SHIFT_SEQUENCE = True
EXPLORE_MIN_ROW_BEFORE_TURN_M = 0.38
EXPLORE_FRONT_TURN_CONFIRM_FRAMES = 3
EXPLORE_TURN_SIDE_HYSTERESIS_M = 0.08
MATRIX_COVERAGE_MIN_PERCENT = 28.0
MATRIX_COVERAGE_MIN_TIME_SEC = 65.0
MAP_BUILDING_UNTIL_COVERAGE_PERCENT = 28.0
MAP_BUILDING_MIN_TIME_SEC = 65.0
WALL_TO_WALL_SWEEP_DISABLE_FIXED_ROW_TURNS = True
EXPLORE_BUMPER_FIRST_MAPPING = True
EXPLORE_BUMPER_FIRST_SPEED = min(CRUISE_SPEED, 2.35)
EXPLORE_PRECONTACT_SLOW_FRONT_M = 0.56
EXPLORE_PRECONTACT_CREEP_FRONT_M = 0.28
EXPLORE_PRECONTACT_SOFT_SPEED = 1.35
EXPLORE_PRECONTACT_CREEP_SPEED = 0.62
EXPLORE_PRECONTACT_BODY_SOFT_M = 0.090
EXPLORE_PRECONTACT_BODY_CREEP_M = 0.055
EXPAND_MAP_EXTENDS_BUMPER_FIRST_MAPPING = True
EXPAND_MAP_MOTION_MIN_FRONTIER_CELLS = PLANNER_INTENT_EXPAND_FRONTIER_CELLS
EXPAND_MAP_MOTION_MAX_COVERAGE_PERCENT = MAP_MATURE_COVERAGE_PERCENT
EXPLORE_CONTACT_BACKUP_GOAL_M = 0.072
EXPLORE_CONTACT_BACKUP_TIMEOUT_SEC = 0.38
EXPLORE_CONTACT_FORWARD_VERIFY_M = 0.000
CONTACT_BACKUP_GUARD_BYPASS_M = 0.035
CONTACT_BACKUP_GUARD_BYPASS_SPEED = 0.18
CONTACT_BACKUP_GUARD_STUCK_PIVOT_AFTER_SEC = 0.30
CONTACT_BACKUP_FRONT_MAPEDGE_RELEASE_M = 0.075
CONTACT_BACKUP_FRONT_MAPEDGE_RELEASE_TIMEOUT_SEC = 0.62
CONTACT_BACKUP_FRONT_MAPEDGE_RELEASE_SPEED = 0.16
CONTACT_BACKUP_FRONT_MAPEDGE_PIVOT_REASON = "front-bump-mapedge-unwedge-pivot"
CONTACT_BACKUP_FRONT_REAROCC_PIVOT_REASON = "front-bump-rear-occupied-pivot"
CONTACT_BACKUP_FRONT_REAROCC_PIVOT_FREEZE_SEC = 0.45
PRE_TURN_REALIGN_ERR = math.radians(4.0)
EXPLORE_ANTI_REVISIT_ENABLED = False
EXPLORE_ANTI_REVISIT_MIN_ROW_M = 1.25
EXPLORE_ANTI_REVISIT_COOLDOWN_SEC = 3.2
EXPLORE_ANTI_REVISIT_CLEANED_AHEAD = 0.40
EXPLORE_ANTI_REVISIT_RECENT_AHEAD = 0.25
EXPLORE_ANTI_REVISIT_MIN_SIDE_SCORE = 0.025
EXPLORE_ANTI_REVISIT_SIDE_MARGIN = 0.015
EXPLORE_ANTI_REVISIT_MIN_SIDE_DEPTH_M = 0.42
EXPLORE_ANTI_REVISIT_SCAN_AHEAD_M = 1.95
EXPLORE_ANTI_REVISIT_SCAN_WIDTH_M = 0.48
EXPLORE_INFO_GAIN_CONTACT_SIDE_ENABLED = False
EXPLORE_INFO_GAIN_SCAN_AHEAD_M = 2.40
EXPLORE_INFO_GAIN_SCAN_WIDTH_M = 0.56
EXPLORE_INFO_GAIN_MIN_SAMPLES = 6
EXPLORE_INFO_GAIN_SIDE_DEPTH_MIN_M = 0.24
EXPLORE_INFO_GAIN_DEPTH_BONUS_M = 1.00
EXPLORE_INFO_GAIN_SIDE_MARGIN = 0.055
EXPLORE_INFO_GAIN_RAW_UNKNOWN_WEIGHT = 0.12
EXPLORE_INFO_GAIN_FRONTIER_WEIGHT = 2.25
EXPLORE_INFO_GAIN_OUTSIDE_WALL_UNKNOWN_PENALTY = 0.85
EXPLORE_ANTI_REVISIT_LATE_PERCENT = 101.0
MAP_BUILDING_DISABLE_LEG_ESCAPE_FSM = True
EXPLORE_LOOP_BREAKER_ENABLED = False
EXPLORE_LOOP_BREAKER_MIN_COVERAGE_PERCENT = 26.0
EXPLORE_LOOP_BREAKER_MIN_ROW_M = 0.95
EXPLORE_LOOP_BREAKER_MIN_FRONT_OPEN_M = 0.55
EXPLORE_LOOP_BREAKER_REQUIRE_SIDE_FRONTIER = 0.010
EXPLORE_LOOP_BREAKER_LONG_OPEN_ROW_M = 3.25
BOUNDARY_TRACE_PERIMETER_FIRST_ENABLED = True
BOUNDARY_TRACE_FOLLOW_SIDE = -1.0
BOUNDARY_TRACE_FRONT_CONTACT_TURN_SIDE = 1.0
BOUNDARY_TRACE_SIDE_OPEN_MARGIN_M = 0.12
BOUNDARY_TRACE_STRICT_SIDE_LOCK_ENABLED = True
BOUNDARY_TRACE_OPPOSITE_EMERGENCY_CENTER_M = ROBOT_BODY_RADIUS + 0.025
BOUNDARY_TRACE_OPPOSITE_EMERGENCY_DEPTH_M = 0.075
MAP_BUILD_WALL_FOLLOW_ENABLED = False
MAP_BUILD_WALL_FOLLOW_MAX_HEADING_ERR = math.radians(6.0)
CONTACT_SIDE_RELEASE_ENABLED = True
CONTACT_SIDE_RELEASE_TURN_ANGLE = math.radians(26.0)
CONTACT_SIDE_RELEASE_MIN_BACKUP_M = 0.050
CONTACT_SIDE_RELEASE_MAX_BACKUP_SEC = 0.42
CONTACT_SIDE_RELEASE_FRONT_CLEAR_M = 0.16
CONTACT_SIDE_RELEASE_CENTER_CLEAR_M = 0.16
CONTACT_SIDE_RELEASE_BODY_CLEAR_M = 0.030
CONTACT_SIDE_RELEASE_SPEED_SCALE = 0.82
CONTACT_SIDE_RELEASE_REVERSE_PIVOT_BIAS = 0.16
CONTACT_SIDE_RELEASE_ROTATE_WATCHDOG_SEC = 2.20
EXPLORE_CONTACT_FORCE_PIVOT_AFTER_M = 0.052
EXPLORE_CONTACT_FORCE_PIVOT_AFTER_SEC = 0.36
EXPLORE_CONTACT_REVERSE_PIVOT_BIAS = 0.26
EXPLORE_CONTACT_REVERSE_PIVOT_MAX_SPEED = 1.12
BODY_ROW_END_LATERAL_TOL_M = 0.060
BODY_ROW_END_FRONT_SUPPORT_M = 0.22
BODY_ROW_END_CENTER_SUPPORT_M = 0.24
BODY_ROW_END_UPPER_SUPPORT_M = 0.30
AUTO_SAVE_ON_DOCK_RETURN = True
AUTO_SAVE_ON_SIM_END = True
ROUTE_COLOR = (255, 90, 255)
ROUTE_WAYPOINT_COLOR = (0, 210, 255)
UNCLEANED_COLOR = (255, 225, 165)
FRONTIER_COLOR = (230, 210, 255)
TARGET_COLOR = (255, 255, 0)
CANDIDATE_TARGET_COLOR = (185, 185, 80)
ACTIVE_TARGET_COLOR = (0, 120, 255)
UNDER_SURFACE_COLOR = (150, 245, 255)
RF_FOV = 1.22
